using System.Collections.Generic;

namespace SenseOfDirection.Ui.Localization.Config
{
    /// <summary>Localized names/descriptions for every "General" section config entry.</summary>
    internal static class GeneralConfigLocalization
    {
        internal static void Register(ConfigLocalizationTable.Registry registry)
        {
            void Add(string key, Dictionary<LocalizedText.Language, ConfigLocalizationEntry> table) =>
                registry.Add("General", key, table);

            Add("player-label-placement", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("PLAYER LABEL PLACEMENT", "Where player labels are drawn. {enumval:IndicatorPlacement.Both} (default): as the edge-of-screen label and as a marker on the compass tape at once. {enumval:IndicatorPlacement.OffScreenOnly}: only the edge-of-screen label. {enumval:IndicatorPlacement.CompassOnly}: only the compass marker."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("EMPLACEMENT DES LABELS JOUEURS", "Où les labels des joueurs sont affichés. {enumval:IndicatorPlacement.Both} (par défaut) : à la fois comme label en bord d'écran et comme repère sur la boussole. {enumval:IndicatorPlacement.OffScreenOnly} : uniquement le label en bord d'écran. {enumval:IndicatorPlacement.CompassOnly} : uniquement le repère sur la boussole."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("POSIZIONE ETICHETTA GIOCATORE", "Dove vengono mostrate le etichette dei giocatori. {enumval:IndicatorPlacement.Both} (predefinito): sia come etichetta a bordo schermo sia come indicatore sulla bussola. {enumval:IndicatorPlacement.OffScreenOnly}: solo l'etichetta a bordo schermo. {enumval:IndicatorPlacement.CompassOnly}: solo l'indicatore sulla bussola."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("SPIELERNAMEN-PLATZIERUNG", "Wo Spielernamen angezeigt werden. {enumval:IndicatorPlacement.Both} (Standard): sowohl als Bildschirmrand-Label als auch als Markierung auf dem Kompassband. {enumval:IndicatorPlacement.OffScreenOnly}: nur das Bildschirmrand-Label. {enumval:IndicatorPlacement.CompassOnly}: nur die Kompassmarkierung."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("UBICACIÓN DE ETIQUETA DE JUGADOR", "Dónde se muestran las etiquetas de jugador. {enumval:IndicatorPlacement.Both} (predeterminado): como etiqueta en el borde de la pantalla y como marcador en la brújula a la vez. {enumval:IndicatorPlacement.OffScreenOnly}: solo la etiqueta en el borde de la pantalla. {enumval:IndicatorPlacement.CompassOnly}: solo el marcador en la brújula."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("UBICACIÓN DE ETIQUETA DE JUGADOR", "Dónde se muestran las etiquetas de jugador. {enumval:IndicatorPlacement.Both} (predeterminado): como etiqueta en el borde de la pantalla y como marcador en la brújula a la vez. {enumval:IndicatorPlacement.OffScreenOnly}: solo la etiqueta en el borde de la pantalla. {enumval:IndicatorPlacement.CompassOnly}: solo el marcador en la brújula."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("POSIÇÃO DO RÓTULO DE JOGADOR", "Onde os rótulos dos jogadores são exibidos. {enumval:IndicatorPlacement.Both} (padrão): como rótulo na borda da tela e como marcador na bússola ao mesmo tempo. {enumval:IndicatorPlacement.OffScreenOnly}: apenas o rótulo na borda da tela. {enumval:IndicatorPlacement.CompassOnly}: apenas o marcador na bússola."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("РАЗМЕЩЕНИЕ МЕТКИ ИГРОКА", "Где отображаются метки игроков. {enumval:IndicatorPlacement.Both} (по умолчанию): и как метка у края экрана, и как метка на компасе одновременно. {enumval:IndicatorPlacement.OffScreenOnly}: только метка у края экрана. {enumval:IndicatorPlacement.CompassOnly}: только метка на компасе."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("РОЗМІЩЕННЯ МІТКИ ГРАВЦЯ", "Де відображаються мітки гравців. {enumval:IndicatorPlacement.Both} (за замовчуванням): і як мітка біля краю екрана, і як мітка на компасі одночасно. {enumval:IndicatorPlacement.OffScreenOnly}: лише мітка біля краю екрана. {enumval:IndicatorPlacement.CompassOnly}: лише мітка на компасі."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("玩家标签位置", "玩家标签显示的位置。{enumval:IndicatorPlacement.Both}（默认）：同时显示为屏幕边缘标签和指南针上的标记。{enumval:IndicatorPlacement.OffScreenOnly}：仅显示屏幕边缘标签。{enumval:IndicatorPlacement.CompassOnly}：仅显示指南针标记。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("玩家標籤位置", "玩家標籤顯示的位置。{enumval:IndicatorPlacement.Both}（預設）：同時顯示為螢幕邊緣標籤和指南針上的標記。{enumval:IndicatorPlacement.OffScreenOnly}：僅顯示螢幕邊緣標籤。{enumval:IndicatorPlacement.CompassOnly}：僅顯示指南針標記。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("プレイヤーラベルの配置", "プレイヤーラベルを表示する場所。{enumval:IndicatorPlacement.Both}（デフォルト）：画面端のラベルとコンパス上のマーカーの両方に表示。{enumval:IndicatorPlacement.OffScreenOnly}：画面端のラベルのみ。{enumval:IndicatorPlacement.CompassOnly}：コンパスのマーカーのみ。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("플레이어 라벨 배치", "플레이어 라벨이 표시되는 위치입니다. {enumval:IndicatorPlacement.Both}(기본값): 화면 가장자리 라벨과 나침반 표시를 동시에 표시합니다. {enumval:IndicatorPlacement.OffScreenOnly}: 화면 가장자리 라벨만 표시합니다. {enumval:IndicatorPlacement.CompassOnly}: 나침반 표시만 표시합니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("UMIEJSCOWIENIE ETYKIETY GRACZA", "Gdzie wyświetlane są etykiety graczy. {enumval:IndicatorPlacement.Both} (domyślnie): jednocześnie jako etykieta na krawędzi ekranu i jako znacznik na kompasie. {enumval:IndicatorPlacement.OffScreenOnly}: tylko etykieta na krawędzi ekranu. {enumval:IndicatorPlacement.CompassOnly}: tylko znacznik na kompasie."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("OYUNCU ETİKETİ KONUMU", "Oyuncu etiketlerinin nerede gösterileceği. {enumval:IndicatorPlacement.Both} (varsayılan): hem ekran kenarı etiketi hem de pusuladaki işaretçi olarak aynı anda. {enumval:IndicatorPlacement.OffScreenOnly}: yalnızca ekran kenarı etiketi. {enumval:IndicatorPlacement.CompassOnly}: yalnızca pusula işaretçisi."),
            });

            Add("campfire-placement", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("CAMPFIRE PLACEMENT", "Where the campfire indicator is drawn, using the same {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} choice as {key:General/player-label-placement} ({enumval:IndicatorPlacement.OffScreenOnly} by default)."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("EMPLACEMENT DU FEU DE CAMP", "Où l'indicateur du feu de camp est affiché, avec le même choix {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} que {key:General/player-label-placement} ({enumval:IndicatorPlacement.OffScreenOnly} par défaut)."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("POSIZIONE FALÒ", "Dove viene mostrato l'indicatore del falò, con la stessa scelta {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} di {key:General/player-label-placement} ({enumval:IndicatorPlacement.OffScreenOnly} per impostazione predefinita)."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("LAGERFEUER-PLATZIERUNG", "Wo die Lagerfeuer-Anzeige dargestellt wird, mit derselben {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both}-Auswahl wie {key:General/player-label-placement} (standardmäßig {enumval:IndicatorPlacement.OffScreenOnly})."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("UBICACIÓN DE LA HOGUERA", "Dónde se muestra el indicador de la hoguera, con la misma opción {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} que {key:General/player-label-placement} ({enumval:IndicatorPlacement.OffScreenOnly} de forma predeterminada)."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("UBICACIÓN DE LA FOGATA", "Dónde se muestra el indicador de la fogata, con la misma opción {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} que {key:General/player-label-placement} ({enumval:IndicatorPlacement.OffScreenOnly} de forma predeterminada)."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("POSIÇÃO DA FOGUEIRA", "Onde o indicador da fogueira é exibido, com a mesma escolha {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} de {key:General/player-label-placement} ({enumval:IndicatorPlacement.OffScreenOnly} por padrão)."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("РАЗМЕЩЕНИЕ КОСТРА", "Где отображается индикатор костра, с тем же выбором {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both}, что и {key:General/player-label-placement} (по умолчанию {enumval:IndicatorPlacement.OffScreenOnly})."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("РОЗМІЩЕННЯ БАГАТТЯ", "Де відображається індикатор багаття, з тим самим вибором {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both}, що й {key:General/player-label-placement} (за замовчуванням {enumval:IndicatorPlacement.OffScreenOnly})."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("篝火位置", "篝火指示器显示的位置，使用与 {key:General/player-label-placement} 相同的 {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} 选项（默认 {enumval:IndicatorPlacement.OffScreenOnly}）。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("營火位置", "營火指示器顯示的位置，使用與 {key:General/player-label-placement} 相同的 {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} 選項（預設 {enumval:IndicatorPlacement.OffScreenOnly}）。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("焚き火の配置", "焚き火インジケーターを表示する場所。{key:General/player-label-placement} と同じ {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} の選択肢（デフォルトは {enumval:IndicatorPlacement.OffScreenOnly}）。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("모닥불 배치", "모닥불 표시기가 표시되는 위치입니다. {key:General/player-label-placement}와 동일한 {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} 선택지를 사용합니다(기본값은 {enumval:IndicatorPlacement.OffScreenOnly})."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("UMIEJSCOWIENIE OGNISKA", "Gdzie wyświetlany jest wskaźnik ogniska, z tym samym wyborem {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} co {key:General/player-label-placement} (domyślnie {enumval:IndicatorPlacement.OffScreenOnly})."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("KAMP ATEŞİ KONUMU", "Kamp ateşi göstergesinin nerede gösterileceği; {key:General/player-label-placement} ile aynı {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} seçeneği kullanılır (varsayılan {enumval:IndicatorPlacement.OffScreenOnly})."),
            });

            Add("ping-placement", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("PING PLACEMENT", "Where pings are drawn, using the same {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} choice as {key:General/player-label-placement} ({enumval:IndicatorPlacement.OffScreenOnly} by default)."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("EMPLACEMENT DES PINGS", "Où les pings sont affichés, avec le même choix {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} que {key:General/player-label-placement} ({enumval:IndicatorPlacement.OffScreenOnly} par défaut)."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("POSIZIONE PING", "Dove vengono mostrati i ping, con la stessa scelta {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} di {key:General/player-label-placement} ({enumval:IndicatorPlacement.OffScreenOnly} per impostazione predefinita)."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("PING-PLATZIERUNG", "Wo Pings dargestellt werden, mit derselben {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both}-Auswahl wie {key:General/player-label-placement} (standardmäßig {enumval:IndicatorPlacement.OffScreenOnly})."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("UBICACIÓN DE PINGS", "Dónde se muestran los pings, con la misma opción {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} que {key:General/player-label-placement} ({enumval:IndicatorPlacement.OffScreenOnly} de forma predeterminada)."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("UBICACIÓN DE PINGS", "Dónde se muestran los pings, con la misma opción {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} que {key:General/player-label-placement} ({enumval:IndicatorPlacement.OffScreenOnly} de forma predeterminada)."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("POSIÇÃO DOS PINGS", "Onde os pings são exibidos, com a mesma escolha {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} de {key:General/player-label-placement} ({enumval:IndicatorPlacement.OffScreenOnly} por padrão)."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("РАЗМЕЩЕНИЕ ПИНГОВ", "Где отображаются пинги, с тем же выбором {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both}, что и {key:General/player-label-placement} (по умолчанию {enumval:IndicatorPlacement.OffScreenOnly})."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("РОЗМІЩЕННЯ ПІНГІВ", "Де відображаються пінги, з тим самим вибором {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both}, що й {key:General/player-label-placement} (за замовчуванням {enumval:IndicatorPlacement.OffScreenOnly})."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("呼喊位置", "呼喊显示的位置，使用与 {key:General/player-label-placement} 相同的 {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} 选项（默认 {enumval:IndicatorPlacement.OffScreenOnly}）。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("呼喊位置", "呼喊顯示的位置，使用與 {key:General/player-label-placement} 相同的 {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} 選項（預設 {enumval:IndicatorPlacement.OffScreenOnly}）。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("ピンの配置", "ピンを表示する場所。{key:General/player-label-placement} と同じ {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} の選択肢（デフォルトは {enumval:IndicatorPlacement.OffScreenOnly}）。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("핑 배치", "핑이 표시되는 위치입니다. {key:General/player-label-placement}와 동일한 {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} 선택지를 사용합니다(기본값은 {enumval:IndicatorPlacement.OffScreenOnly})."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("UMIEJSCOWIENIE PINGÓW", "Gdzie wyświetlane są pingi, z tym samym wyborem {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} co {key:General/player-label-placement} (domyślnie {enumval:IndicatorPlacement.OffScreenOnly})."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("PİNG KONUMU", "Pinglerin nerede gösterileceği; {key:General/player-label-placement} ile aynı {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} seçeneği kullanılır (varsayılan {enumval:IndicatorPlacement.OffScreenOnly})."),
            });

            Add("item-ping-placement", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("ITEM PING PLACEMENT", "Where item/luggage/creature ping highlights are drawn, using the same {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} choice as {key:General/player-label-placement} ({enumval:IndicatorPlacement.OffScreenOnly} by default)."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("EMPLACEMENT DES PINGS D'OBJETS", "Où les surbrillances de ping d'objet/bagage/créature sont affichées, avec le même choix {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} que {key:General/player-label-placement} ({enumval:IndicatorPlacement.OffScreenOnly} par défaut)."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("POSIZIONE PING OGGETTI", "Dove vengono mostrate le evidenziazioni dei ping di oggetti/bagagli/creature, con la stessa scelta {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} di {key:General/player-label-placement} ({enumval:IndicatorPlacement.OffScreenOnly} per impostazione predefinita)."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("GEGENSTANDS-PING-PLATZIERUNG", "Wo Hervorhebungen von Gegenstands-/Gepäck-/Kreaturen-Pings dargestellt werden, mit derselben {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both}-Auswahl wie {key:General/player-label-placement} (standardmäßig {enumval:IndicatorPlacement.OffScreenOnly})."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("UBICACIÓN DE PINGS DE OBJETOS", "Dónde se muestran los resaltados de ping de objetos/equipaje/criaturas, con la misma opción {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} que {key:General/player-label-placement} ({enumval:IndicatorPlacement.OffScreenOnly} de forma predeterminada)."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("UBICACIÓN DE PINGS DE OBJETOS", "Dónde se muestran los resaltados de ping de objetos/equipaje/criaturas, con la misma opción {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} que {key:General/player-label-placement} ({enumval:IndicatorPlacement.OffScreenOnly} de forma predeterminada)."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("POSIÇÃO DOS PINGS DE ITENS", "Onde os destaques de ping de itens/bagagens/criaturas são exibidos, com a mesma escolha {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} de {key:General/player-label-placement} ({enumval:IndicatorPlacement.OffScreenOnly} por padrão)."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("РАЗМЕЩЕНИЕ ПИНГОВ ПРЕДМЕТОВ", "Где отображается подсветка пингов предметов/багажа/существ, с тем же выбором {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both}, что и {key:General/player-label-placement} (по умолчанию {enumval:IndicatorPlacement.OffScreenOnly})."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("РОЗМІЩЕННЯ ПІНГІВ ПРЕДМЕТІВ", "Де відображається підсвітка пінгів предметів/багажу/істот, з тим самим вибором {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both}, що й {key:General/player-label-placement} (за замовчуванням {enumval:IndicatorPlacement.OffScreenOnly})."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("物品呼喊位置", "物品/行李/生物呼喊高亮显示的位置，使用与 {key:General/player-label-placement} 相同的 {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} 选项（默认 {enumval:IndicatorPlacement.OffScreenOnly}）。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("物品呼喊位置", "物品/行李/生物呼喊高亮顯示的位置，使用與 {key:General/player-label-placement} 相同的 {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} 選項（預設 {enumval:IndicatorPlacement.OffScreenOnly}）。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("アイテムピンの配置", "アイテム/荷物/クリーチャーのピンハイライトを表示する場所。{key:General/player-label-placement} と同じ {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} の選択肢（デフォルトは {enumval:IndicatorPlacement.OffScreenOnly}）。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("아이템 핑 배치", "아이템/수하물/생물체 핑 강조 표시가 표시되는 위치입니다. {key:General/player-label-placement}와 동일한 {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} 선택지를 사용합니다(기본값은 {enumval:IndicatorPlacement.OffScreenOnly})."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("UMIEJSCOWIENIE PINGÓW PRZEDMIOTÓW", "Gdzie wyświetlane są wyróżnienia pingów przedmiotów/bagażu/stworzeń, z tym samym wyborem {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} co {key:General/player-label-placement} (domyślnie {enumval:IndicatorPlacement.OffScreenOnly})."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("EŞYA PİNGİ KONUMU", "Eşya/bagaj/yaratık ping vurgularının nerede gösterileceği; {key:General/player-label-placement} ile aynı {enumval:IndicatorPlacement.OffScreenOnly}/{enumval:IndicatorPlacement.CompassOnly}/{enumval:IndicatorPlacement.Both} seçeneği kullanılır (varsayılan {enumval:IndicatorPlacement.OffScreenOnly})."),
            });

            Add("enable-label-overlap-avoidance", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("ENABLE LABEL OVERLAP AVOIDANCE", "Nudges overlapping player/ping/item-ping/campfire labels (and compass markers) apart so they stay readable when several land on top of each other, instead of stacking illegibly. Off restores every label/marker to its exact tracked position with no nudging at all."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("ÉVITER LE CHEVAUCHEMENT DES LABELS", "Écarte légèrement les labels de joueur/ping/ping d'objet/feu de camp qui se chevauchent (ainsi que les repères de la boussole) pour qu'ils restent lisibles lorsque plusieurs se superposent, au lieu de s'empiler illisiblement. Désactivé, chaque label/repère reste exactement à sa position suivie, sans aucun décalage."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("ATTIVA PREVENZIONE SOVRAPPOSIZIONE ETICHETTE", "Sposta leggermente le etichette di giocatore/ping/ping oggetto/falò che si sovrappongono (e gli indicatori della bussola) affinché restino leggibili quando più elementi si trovano nello stesso punto, invece di accatastarsi in modo illeggibile. Disattivato, ogni etichetta/indicatore resta esattamente nella sua posizione tracciata, senza alcuno spostamento."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("ÜBERLAPPUNGSVERMEIDUNG FÜR LABELS AKTIVIEREN", "Verschiebt überlappende Spieler-/Ping-/Gegenstands-Ping-/Lagerfeuer-Labels (und Kompassmarkierungen) leicht auseinander, damit sie lesbar bleiben, wenn mehrere aufeinanderliegen, statt unleserlich übereinanderzustapeln. Deaktiviert, bleibt jedes Label/jede Markierung exakt an seiner verfolgten Position, ganz ohne Verschiebung."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("ACTIVAR PREVENCIÓN DE SOLAPAMIENTO DE ETIQUETAS", "Separa ligeramente las etiquetas de jugador/ping/ping de objeto/hoguera que se solapan (y los marcadores de la brújula) para que sigan siendo legibles cuando varias coinciden en el mismo punto, en lugar de amontonarse de forma ilegible. Desactivado, cada etiqueta/marcador permanece exactamente en su posición rastreada, sin ningún desplazamiento."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("ACTIVAR PREVENCIÓN DE SUPERPOSICIÓN DE ETIQUETAS", "Separa ligeramente las etiquetas de jugador/ping/ping de objeto/fogata que se superponen (y los marcadores de la brújula) para que sigan siendo legibles cuando varias coinciden en el mismo punto, en lugar de amontonarse de forma ilegible. Desactivado, cada etiqueta/marcador permanece exactamente en su posición rastreada, sin ningún desplazamiento."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("ATIVAR PREVENÇÃO DE SOBREPOSIÇÃO DE RÓTULOS", "Afasta levemente rótulos de jogador/ping/ping de item/fogueira que se sobrepõem (e marcadores da bússola) para que continuem legíveis quando vários caem no mesmo ponto, em vez de se empilharem de forma ilegível. Desativado, cada rótulo/marcador permanece exatamente em sua posição rastreada, sem nenhum deslocamento."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("ВКЛЮЧИТЬ ИЗБЕГАНИЕ НАЛОЖЕНИЯ МЕТОК", "Слегка раздвигает пересекающиеся метки игроков/пингов/пингов предметов/костра (и метки на компасе), чтобы они оставались читаемыми, когда несколько накладываются друг на друга, вместо нечитаемого нагромождения. При выключении каждая метка остаётся точно на своей отслеживаемой позиции, без какого-либо смещения."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("УВІМКНУТИ УНИКНЕННЯ НАКЛАДАННЯ МІТОК", "Злегка розсуває мітки гравців/пінгів/пінгів предметів/багаття, що перекриваються (та мітки на компасі), щоб вони залишалися читабельними, коли кілька накладаються одна на одну, замість нечитабельного нагромадження. Якщо вимкнено, кожна мітка залишається точно на своїй відстежуваній позиції, без жодного зсуву."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("启用标签防重叠", "当多个玩家/呼喊/物品呼喊/篝火标签（以及指南针标记）重叠在一起时，轻微错开它们以保持可读性，而不是难以辨认地堆叠在一起。关闭后，每个标签/标记都会保持在其精确的追踪位置，完全不做任何偏移。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("啟用標籤防重疊", "當多個玩家/呼喊/物品呼喊/營火標籤（以及指南針標記）重疊在一起時，輕微錯開它們以保持可讀性，而不是難以辨識地堆疊在一起。關閉後，每個標籤/標記都會保持在其精確的追蹤位置，完全不做任何偏移。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("ラベル重なり回避を有効化", "プレイヤー/ピン/アイテムピン/焚き火のラベル（およびコンパスのマーカー）が重なったとき、判読不能に積み重なる代わりに少しずらして読みやすさを保ちます。オフにすると、すべてのラベル/マーカーはずれることなく、追跡している正確な位置に表示されます。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("라벨 겹침 방지 활성화", "여러 플레이어/핑/아이템 핑/모닥불 라벨(및 나침반 표시)이 겹칠 때 읽을 수 없게 쌓이는 대신 조금씩 밀어내어 가독성을 유지합니다. 끄면 모든 라벨/표시가 밀림 없이 정확히 추적된 위치에 그대로 표시됩니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("WŁĄCZ UNIKANIE NAKŁADANIA SIĘ ETYKIET", "Lekko rozsuwa nakładające się etykiety gracza/pingu/pingu przedmiotu/ogniska (oraz znaczniki kompasu), aby pozostały czytelne, gdy kilka z nich znajdzie się w tym samym miejscu, zamiast nieczytelnie się piętrzyć. Po wyłączeniu każda etykieta/znacznik pozostaje dokładnie w swojej śledzonej pozycji, bez żadnego przesunięcia."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("ETİKET ÇAKIŞMASINI ÖNLEMEYİ ETKİNLEŞTİR", "Üst üste binen oyuncu/ping/eşya pingi/kamp ateşi etiketlerini (ve pusula işaretçilerini) okunaksız biçimde yığılmak yerine okunabilir kalmaları için hafifçe birbirinden ayırır. Kapalıyken her etiket/işaretçi, hiçbir kaydırma olmadan tam olarak izlenen konumunda kalır."),
            });

            Add("preview-menu-key", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("PREVIEW MENU KEY", "Key that opens the in-game settings menu: every visual setting in this mod, laid out over a live preview of what it actually does (player labels, pings, item pings, the campfire indicator and the compass, all drawn on a real screenshot and updating as you change them). Changes there are written straight to this config file. Set to None to disable the key entirely."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("TOUCHE DU MENU D'APERÇU", "Touche qui ouvre le menu de paramètres en jeu : tous les paramètres visuels de ce mod, présentés au-dessus d'un aperçu en direct de leur effet réel (labels de joueurs, pings, pings d'objets, indicateur du feu de camp et boussole, tous dessinés sur une vraie capture d'écran et mis à jour au fur et à mesure des changements). Les modifications y sont écrites directement dans ce fichier de configuration. Réglez sur None pour désactiver complètement la touche."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("TASTO MENU ANTEPRIMA", "Tasto che apre il menu delle impostazioni in gioco: tutte le impostazioni visive di questa mod, disposte sopra un'anteprima dal vivo di ciò che fanno realmente (etichette giocatori, ping, ping oggetti, indicatore del falò e bussola, tutti disegnati su uno screenshot reale e aggiornati man mano che li modifichi). Le modifiche vengono scritte direttamente in questo file di configurazione. Imposta su None per disattivare completamente il tasto."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("VORSCHAUMENÜ-TASTE", "Taste, die das Einstellungsmenü im Spiel öffnet: jede visuelle Einstellung dieses Mods, dargestellt über einer Live-Vorschau dessen, was sie tatsächlich bewirkt (Spielernamen, Pings, Gegenstands-Pings, Lagerfeuer-Anzeige und Kompass, alle auf einem echten Screenshot gezeichnet und live aktualisiert, während du sie änderst). Änderungen werden dort direkt in diese Konfigurationsdatei geschrieben. Auf None setzen, um die Taste vollständig zu deaktivieren."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("TECLA DEL MENÚ DE VISTA PREVIA", "Tecla que abre el menú de ajustes del juego: todos los ajustes visuales de este mod, mostrados sobre una vista previa en vivo de lo que realmente hacen (etiquetas de jugador, pings, pings de objetos, indicador de la hoguera y brújula, todos dibujados sobre una captura de pantalla real y actualizados a medida que los cambias). Los cambios se escriben directamente en este archivo de configuración. Ajusta a None para desactivar la tecla por completo."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("TECLA DEL MENÚ DE VISTA PREVIA", "Tecla que abre el menú de ajustes del juego: todos los ajustes visuales de este mod, mostrados sobre una vista previa en vivo de lo que realmente hacen (etiquetas de jugador, pings, pings de objetos, indicador de la fogata y brújula, todos dibujados sobre una captura de pantalla real y actualizados a medida que los cambias). Los cambios se escriben directamente en este archivo de configuración. Ajusta a None para desactivar la tecla por completo."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("TECLA DO MENU DE PRÉVIA", "Tecla que abre o menu de configurações no jogo: cada configuração visual deste mod, exibida sobre uma prévia ao vivo do que ela realmente faz (rótulos de jogador, pings, pings de itens, indicador da fogueira e bússola, todos desenhados sobre uma captura de tela real e atualizados conforme você os altera). As alterações são gravadas diretamente neste arquivo de configuração. Defina como None para desativar a tecla por completo."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("КЛАВИША МЕНЮ ПРЕДПРОСМОТРА", "Клавиша, открывающая игровое меню настроек: все визуальные настройки этого мода отображаются поверх живого предпросмотра того, что они реально делают (метки игроков, пинги, пинги предметов, индикатор костра и компас — всё рисуется поверх настоящего скриншота и обновляется при изменении настроек). Изменения тут же записываются в этот файл конфигурации. Установите None, чтобы полностью отключить клавишу."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("КЛАВІША МЕНЮ ПОПЕРЕДНЬОГО ПЕРЕГЛЯДУ", "Клавіша, що відкриває ігрове меню налаштувань: усі візуальні налаштування цього мода відображаються поверх живого попереднього перегляду того, що вони реально роблять (мітки гравців, пінги, пінги предметів, індикатор багаття та компас — усе малюється поверх справжнього скріншота й оновлюється при зміні налаштувань). Зміни одразу записуються в цей файл конфігурації. Встановіть None, щоб повністю вимкнути клавішу."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("预览菜单按键", "打开游戏内设置菜单的按键：本模组的每一项视觉设置都会显示在其实际效果的实时预览之上（玩家标签、呼喊、物品呼喊、篝火指示器和指南针，全部绘制在真实截图上并随设置变化实时更新）。在此处所做的更改会直接写入此配置文件。设为 None 可完全禁用该按键。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("預覽選單按鍵", "開啟遊戲內設定選單的按鍵：本模組的每項視覺設定都會顯示在其實際效果的即時預覽之上（玩家標籤、呼喊、物品呼喊、營火指示器和指南針，全部繪製在真實截圖上並隨設定變化即時更新）。在此處所做的變更會直接寫入此設定檔。設為 None 可完全停用該按鍵。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("プレビューメニューキー", "ゲーム内設定メニューを開くキー。このMODのすべてのビジュアル設定が、実際の効果のライブプレビュー（プレイヤーラベル、ピン、アイテムピン、焚き火インジケーター、コンパス、すべて実際のスクリーンショット上に描画され、変更するたびに更新されます）の上に配置されます。そこでの変更はこの設定ファイルに直接書き込まれます。キーを完全に無効化するには None に設定してください。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("미리보기 메뉴 키", "게임 내 설정 메뉴를 여는 키입니다. 이 모드의 모든 시각적 설정이 실제 동작의 실시간 미리보기(플레이어 라벨, 핑, 아이템 핑, 모닥불 표시기, 나침반이 모두 실제 스크린샷 위에 그려지고 변경할 때마다 업데이트됨) 위에 표시됩니다. 여기서의 변경 사항은 이 설정 파일에 바로 기록됩니다. 키를 완전히 비활성화하려면 None으로 설정하세요."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("KLAWISZ MENU PODGLĄDU", "Klawisz otwierający menu ustawień w grze: każde ustawienie wizualne tego moda przedstawione na żywym podglądzie tego, co faktycznie robi (etykiety graczy, pingi, pingi przedmiotów, wskaźnik ogniska i kompas — wszystko narysowane na prawdziwym zrzucie ekranu i aktualizowane na bieżąco podczas zmian). Zmiany są tam zapisywane bezpośrednio do tego pliku konfiguracyjnego. Ustaw None, aby całkowicie wyłączyć klawisz."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("ÖNİZLEME MENÜSÜ TUŞU", "Oyun içi ayarlar menüsünü açan tuş: bu moddaki her görsel ayar, gerçekte ne yaptığının canlı bir önizlemesi üzerinde gösterilir (oyuncu etiketleri, pingler, eşya pingleri, kamp ateşi göstergesi ve pusula; hepsi gerçek bir ekran görüntüsü üzerine çizilir ve ayarları değiştirdikçe güncellenir). Buradaki değişiklikler doğrudan bu yapılandırma dosyasına yazılır. Tuşu tamamen devre dışı bırakmak için None olarak ayarlayın."),
            });
        }
    }
}
