using System.Collections.Generic;

namespace SenseOfDirection.Ui.Localization.Config
{
    /// <summary>Localized names/descriptions for every "Ghost-Free-Cam" section config entry.</summary>
    internal static class GhostFreeCamConfigLocalization
    {
        internal static void Register(ConfigLocalizationTable.Registry registry)
        {
            void Add(string key, Dictionary<LocalizedText.Language, ConfigLocalizationEntry> table) =>
                registry.Add("Ghost-Free-Cam", key, table);

            Add("enable-ghost-free-cam", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("ENABLE GHOST FREE-CAM", "Lets dead players fly a free camera instead of being stuck in vanilla's third-person spectate view. Unlike every other setting in this mod, this one and the two below it are host-controlled: only the room host's own value for these three settings ever takes effect for every player, the same way {key:Pings/enable-ghost-ping} requires both sides to have this mod installed. That's because letting each client fly unlimited distances would be an unfair, effectively ESP-like advantage other players in the same run never agreed to. If the host doesn't have this mod installed, ghost free-cam simply doesn't work for anyone, same as ghost pinging. Your own value here still matters if you end up being the host."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("ACTIVER LA CAMÉRA LIBRE FANTÔME", "Permet aux joueurs morts de piloter une caméra libre au lieu d'être bloqués dans la vue spectateur à la troisième personne du jeu de base. Contrairement à tout autre réglage de ce mod, celui-ci et les deux suivants sont contrôlés par l'hôte : seule la valeur de l'hôte de la partie pour ces trois réglages s'applique à tous les joueurs, de la même façon qu'{key:Pings/enable-ghost-ping} exige que les deux côtés aient ce mod installé. C'est parce que laisser chaque client voler sur des distances illimitées serait un avantage injuste, pratiquement comme un ESP, que les autres joueurs de la même partie n'ont jamais accepté. Si l'hôte n'a pas ce mod installé, la caméra libre fantôme ne fonctionne tout simplement pour personne, comme pour le ping fantôme. Votre propre valeur ici compte quand même si vous finissez par être l'hôte."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("ATTIVA TELECAMERA LIBERA FANTASMA", "Permette ai giocatori morti di pilotare una telecamera libera invece di rimanere bloccati nella vista spettatore in terza persona del gioco base. A differenza di ogni altra impostazione di questa mod, questa e le due sottostanti sono controllate dall'host: solo il valore dell'host della stanza per queste tre impostazioni ha effetto per tutti i giocatori, allo stesso modo in cui {key:Pings/enable-ghost-ping} richiede che entrambe le parti abbiano questa mod installata. Questo perché permettere a ogni client di volare a distanze illimitate sarebbe un vantaggio ingiusto, praticamente come un ESP, che gli altri giocatori della stessa partita non hanno mai accettato. Se l'host non ha questa mod installata, la telecamera libera fantasma semplicemente non funziona per nessuno, come per il ping fantasma. Il tuo valore qui conta comunque se finisci per essere l'host."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("GEISTER-FREIKAMERA AKTIVIEREN", "Erlaubt toten Spielern, eine Freikamera zu fliegen, anstatt in der Third-Person-Zuschaueransicht des Originalspiels festzustecken. Anders als jede andere Einstellung in diesem Mod werden diese und die beiden darunter vom Host gesteuert: Nur der Wert des Raum-Hosts für diese drei Einstellungen gilt für jeden Spieler, genauso wie {key:Pings/enable-ghost-ping} erfordert, dass beide Seiten diesen Mod installiert haben. Der Grund: Jedem Client unbegrenzte Flugdistanzen zu erlauben, wäre ein unfairer, praktisch ESP-artiger Vorteil, dem andere Spieler in derselben Runde nie zugestimmt haben. Hat der Host diesen Mod nicht installiert, funktioniert die Geister-Freikamera für niemanden, genau wie Geister-Pings. Dein eigener Wert hier zählt trotzdem, falls du selbst zum Host wirst."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("ACTIVAR CÁMARA LIBRE FANTASMA", "Permite a los jugadores muertos volar con una cámara libre en lugar de quedar atrapados en la vista de espectador en tercera persona del juego base. A diferencia de cualquier otro ajuste de este mod, este y los dos siguientes están controlados por el anfitrión: solo el valor del anfitrión de la sala para estos tres ajustes surte efecto para todos los jugadores, del mismo modo que {key:Pings/enable-ghost-ping} requiere que ambas partes tengan este mod instalado. Esto es porque dejar que cada cliente vuele distancias ilimitadas sería una ventaja injusta, prácticamente como un ESP, que otros jugadores de la misma partida nunca aceptaron. Si el anfitrión no tiene este mod instalado, la cámara libre fantasma simplemente no funciona para nadie, igual que el ping fantasma. Tu propio valor aquí sigue importando si terminas siendo el anfitrión."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("ACTIVAR CÁMARA LIBRE FANTASMA", "Permite a los jugadores muertos volar con una cámara libre en lugar de quedar atrapados en la vista de espectador en tercera persona del juego base. A diferencia de cualquier otro ajuste de este mod, este y los dos siguientes están controlados por el anfitrión: solo el valor del anfitrión de la sala para estos tres ajustes surte efecto para todos los jugadores, del mismo modo que {key:Pings/enable-ghost-ping} requiere que ambas partes tengan este mod instalado. Esto es porque dejar que cada cliente vuele distancias ilimitadas sería una ventaja injusta, prácticamente como un ESP, que otros jugadores de la misma partida nunca aceptaron. Si el anfitrión no tiene este mod instalado, la cámara libre fantasma simplemente no funciona para nadie, igual que el ping fantasma. Tu propio valor aquí sigue importando si terminas siendo el anfitrión."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("ATIVAR CÂMERA LIVRE FANTASMA", "Permite que jogadores mortos pilotem uma câmera livre em vez de ficarem presos na visão de espectador em terceira pessoa do jogo original. Diferente de qualquer outra configuração deste mod, esta e as duas abaixo são controladas pelo anfitrião: apenas o valor do anfitrião da sala para essas três configurações tem efeito para todos os jogadores, da mesma forma que {key:Pings/enable-ghost-ping} exige que ambos os lados tenham este mod instalado. Isso porque deixar cada cliente voar distâncias ilimitadas seria uma vantagem injusta, praticamente como um ESP, que outros jogadores da mesma partida nunca concordaram. Se o anfitrião não tiver este mod instalado, a câmera livre fantasma simplesmente não funciona para ninguém, assim como o ping fantasma. Seu próprio valor aqui ainda importa caso você acabe sendo o anfitrião."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("ВКЛЮЧИТЬ СВОБОДНУЮ КАМЕРУ ПРИЗРАКА", "Позволяет погибшим игрокам летать на свободной камере вместо того, чтобы быть запертыми в стандартном виде наблюдателя от третьего лица. В отличие от всех остальных настроек этого мода, эта и две ниже управляются хостом: только значение хоста комнаты для этих трёх настроек действует для всех игроков, точно так же как {key:Pings/enable-ghost-ping} требует, чтобы мод был установлен у обеих сторон. Причина в том, что разрешение каждому клиенту летать на неограниченные расстояния было бы нечестным, по сути ESP-подобным преимуществом, на которое другие игроки той же игры никогда не соглашались. Если у хоста этот мод не установлен, свободная камера призрака просто не работает ни у кого, как и призрачный пинг. Ваше собственное значение здесь всё равно важно, если вы в итоге станете хостом."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("УВІМКНУТИ ВІЛЬНУ КАМЕРУ ПРИВИДА", "Дозволяє загиблим гравцям літати вільною камерою замість того, щоб бути замкненими у стандартному вигляді спостерігача від третьої особи. На відміну від усіх інших налаштувань цього мода, це і два нижче керуються хостом: лише значення хоста кімнати для цих трьох налаштувань діє для всіх гравців, так само як {key:Pings/enable-ghost-ping} вимагає, щоб мод був встановлений в обох сторін. Причина в тому, що дозвіл кожному клієнту літати на необмежені відстані був би нечесною, по суті ESP-подібною перевагою, на яку інші гравці тієї ж гри ніколи не погоджувалися. Якщо в хоста цей мод не встановлено, вільна камера привида просто не працює ні в кого, так само як привидний пінг. Ваше власне значення тут все одно важливе, якщо ви врешті станете хостом."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("启用幽灵自由视角", "让死亡玩家可以自由飞行摄像机，而不是被困在原版的第三人称旁观视角中。与本模组中的所有其他设置不同，此设置及以下两项由房主控制：只有房主对这三项设置的值才会对所有玩家生效，这与 {key:Pings/enable-ghost-ping} 要求双方都安装本模组的方式相同。原因是，允许每个客户端无限距离飞行将是一种不公平的、实质上类似透视外挂的优势，而同一局中的其他玩家从未同意过这一点。如果房主未安装本模组，幽灵自由视角对任何人都不起作用，就像幽灵呼喊一样。如果你最终成为房主，这里的设置值仍然重要。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("啟用幽靈自由視角", "讓死亡玩家可以自由飛行攝影機，而不是被困在原版的第三人稱旁觀視角中。與本模組中的所有其他設定不同，此設定及以下兩項由房主控制：只有房主對這三項設定的值才會對所有玩家生效，這與 {key:Pings/enable-ghost-ping} 要求雙方都安裝本模組的方式相同。原因是，允許每個客戶端無限距離飛行將是一種不公平的、實質上類似透視外掛的優勢，而同一局中的其他玩家從未同意過這一點。如果房主未安裝本模組，幽靈自由視角對任何人都不起作用，就像幽靈呼喊一樣。如果你最終成為房主，這裡的設定值仍然重要。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("ゴーストフリーカムを有効化", "死亡したプレイヤーが、バニラの三人称観戦視点に固定される代わりにフリーカメラで飛び回れるようにします。このMODの他の設定と異なり、この設定とその下の2つはホスト制御です。これら3つの設定はルームホスト自身の値のみが全プレイヤーに適用され、{key:Pings/enable-ghost-ping}が双方にこのMODのインストールを要求するのと同じ仕組みです。理由は、各クライアントが無制限の距離を飛べるようにすると、同じセッションの他のプレイヤーが同意していない、事実上ESPのような不公平な優位性になってしまうためです。ホストがこのMODをインストールしていない場合、ゴーストピンと同様にゴーストフリーカムは誰に対しても機能しません。自分がホストになった場合は、ここでの自分の設定値が引き続き重要になります。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("고스트 프리캠 활성화", "사망한 플레이어가 바닐라의 3인칭 관전 시점에 갇히는 대신 자유 카메라로 비행할 수 있게 합니다. 이 모드의 다른 모든 설정과 달리, 이 설정과 아래 두 설정은 호스트가 제어합니다. 이 세 설정에 대해서는 방 호스트의 값만이 모든 플레이어에게 적용되며, 이는 {key:Pings/enable-ghost-ping}이 양쪽 모두 이 모드를 설치해야 하는 것과 같은 방식입니다. 이는 각 클라이언트가 무제한 거리로 비행하도록 허용하면 같은 게임의 다른 플레이어들이 동의한 적 없는, 사실상 ESP와 같은 불공정한 이점이 되기 때문입니다. 호스트가 이 모드를 설치하지 않았다면, 고스트 핑과 마찬가지로 고스트 프리캠은 누구에게도 작동하지 않습니다. 여러분이 결국 호스트가 되는 경우에는 여기의 값이 여전히 중요합니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("WŁĄCZ WOLNĄ KAMERĘ DUCHA", "Pozwala martwym graczom latać wolną kamerą zamiast być uwięzionym w standardowym widoku obserwatora trzeciej osoby. W przeciwieństwie do każdego innego ustawienia w tym modzie, to i dwa poniższe są kontrolowane przez hosta: tylko wartość hosta pokoju dla tych trzech ustawień ma efekt dla wszystkich graczy, tak samo jak {key:Pings/enable-ghost-ping} wymaga, aby obie strony miały zainstalowany ten mod. Powód: pozwolenie każdemu klientowi na latanie na nieograniczone odległości byłoby nieuczciwą, praktycznie ESP-podobną przewagą, na którą inni gracze w tej samej rozgrywce nigdy się nie zgodzili. Jeśli host nie ma zainstalowanego tego moda, wolna kamera ducha po prostu nie działa dla nikogo, tak samo jak pingi ducha. Twoja własna wartość tutaj nadal ma znaczenie, jeśli sam zostaniesz hostem."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("HAYALET SERBEST KAMERAYI ETKİNLEŞTİR", "Ölü oyuncuların, oyunun standart üçüncü şahıs izleyici görünümünde sıkışıp kalmak yerine serbest bir kamerayla uçmasını sağlar. Bu moddaki diğer tüm ayarların aksine, bu ayar ve altındaki iki ayar sunucu (host) tarafından kontrol edilir: bu üç ayar için yalnızca oda sahibinin (host) değeri tüm oyuncular için geçerli olur; tıpkı {key:Pings/enable-ghost-ping} ayarının her iki tarafın da bu modu kurmuş olmasını gerektirmesi gibi. Bunun nedeni, her istemcinin sınırsız mesafede uçmasına izin vermenin, aynı oyundaki diğer oyuncuların asla kabul etmediği, etkin biçimde ESP benzeri haksız bir avantaj olmasıdır. Host bu modu kurmamışsa, hayalet pinglemede olduğu gibi hayalet serbest kamera kimse için çalışmaz. Kendi değeriniz, siz host olursanız yine önemli olur."),
            });

            Add("max-distance-meters", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("MAX DISTANCE METERS", "Host-controlled, see {key:Ghost-Free-Cam/enable-ghost-free-cam}. How far a ghost's free camera can scout from whichever living player they're currently spectating before being pulled back, like a chain of this length. Ignored entirely when {key:Ghost-Free-Cam/unlimited-range} is on."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("DISTANCE MAX EN MÈTRES", "Contrôlé par l'hôte, voir {key:Ghost-Free-Cam/enable-ghost-free-cam}. Jusqu'où la caméra libre d'un fantôme peut explorer depuis le joueur vivant qu'il observe actuellement avant d'être ramenée en arrière, comme une chaîne de cette longueur. Complètement ignoré quand {key:Ghost-Free-Cam/unlimited-range} est activé."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("DISTANZA MASSIMA IN METRI", "Controllato dall'host, vedi {key:Ghost-Free-Cam/enable-ghost-free-cam}. Quanto lontano può esplorare la telecamera libera di un fantasma dal giocatore vivo che sta attualmente osservando prima di essere riportata indietro, come una catena di questa lunghezza. Completamente ignorato quando {key:Ghost-Free-Cam/unlimited-range} è attivo."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("MAXIMALE ENTFERNUNG IN METERN", "Vom Host gesteuert, siehe {key:Ghost-Free-Cam/enable-ghost-free-cam}. Wie weit sich die Freikamera eines Geistes von dem lebenden Spieler entfernen kann, den er gerade beobachtet, bevor sie zurückgezogen wird, wie an einer Kette dieser Länge. Wird bei aktiviertem {key:Ghost-Free-Cam/unlimited-range} komplett ignoriert."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("DISTANCIA MÁXIMA EN METROS", "Controlado por el anfitrión, ver {key:Ghost-Free-Cam/enable-ghost-free-cam}. Hasta dónde puede explorar la cámara libre de un fantasma desde el jugador vivo que está observando actualmente antes de ser jalada de vuelta, como una cadena de esta longitud. Se ignora por completo cuando {key:Ghost-Free-Cam/unlimited-range} está activado."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("DISTANCIA MÁXIMA EN METROS", "Controlado por el anfitrión, ver {key:Ghost-Free-Cam/enable-ghost-free-cam}. Hasta dónde puede explorar la cámara libre de un fantasma desde el jugador vivo que está observando actualmente antes de ser jalada de vuelta, como una cadena de esta longitud. Se ignora por completo cuando {key:Ghost-Free-Cam/unlimited-range} está activado."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("DISTÂNCIA MÁXIMA EM METROS", "Controlado pelo anfitrião, veja {key:Ghost-Free-Cam/enable-ghost-free-cam}. Até onde a câmera livre de um fantasma pode explorar a partir do jogador vivo que está observando no momento antes de ser puxada de volta, como uma corrente desse comprimento. Totalmente ignorado quando {key:Ghost-Free-Cam/unlimited-range} está ativado."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("МАКС. ДИСТАНЦИЯ В МЕТРАХ", "Управляется хостом, см. {key:Ghost-Free-Cam/enable-ghost-free-cam}. Как далеко свободная камера призрака может отойти от живого игрока, за которым она сейчас наблюдает, прежде чем её оттянет назад, как цепь такой длины. Полностью игнорируется, когда включён {key:Ghost-Free-Cam/unlimited-range}."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("МАКС. ВІДСТАНЬ У МЕТРАХ", "Керується хостом, див. {key:Ghost-Free-Cam/enable-ghost-free-cam}. Наскільки далеко вільна камера привида може відійти від живого гравця, за яким вона наразі спостерігає, перш ніж її потягне назад, як ланцюг такої довжини. Повністю ігнорується, коли увімкнено {key:Ghost-Free-Cam/unlimited-range}."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("最大距离（米）", "由房主控制，参见 {key:Ghost-Free-Cam/enable-ghost-free-cam}。幽灵自由摄像机在被拉回之前，可以离当前正在观察的存活玩家多远，就像这个长度的链条一样。启用 {key:Ghost-Free-Cam/unlimited-range} 时此设置完全被忽略。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("最大距離（公尺）", "由房主控制，參見 {key:Ghost-Free-Cam/enable-ghost-free-cam}。幽靈自由攝影機在被拉回之前，可以離當前正在觀察的存活玩家多遠，就像這個長度的鏈條一樣。啟用 {key:Ghost-Free-Cam/unlimited-range} 時此設定完全被忽略。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("最大距離（メートル）", "ホスト制御、{key:Ghost-Free-Cam/enable-ghost-free-cam}を参照。ゴーストのフリーカメラが、現在観戦している生存プレイヤーから引き戻されるまでにどれだけ離れられるか（この長さの鎖のようなもの）。{key:Ghost-Free-Cam/unlimited-range}がオンの場合は完全に無視されます。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("최대 거리(미터)", "호스트가 제어함, {key:Ghost-Free-Cam/enable-ghost-free-cam} 참조. 고스트의 프리캠이 다시 끌려오기 전까지 현재 관전 중인 생존 플레이어로부터 이 길이의 사슬처럼 얼마나 멀리 정찰할 수 있는지입니다. {key:Ghost-Free-Cam/unlimited-range}가 켜져 있으면 완전히 무시됩니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("MAKSYMALNA ODLEGŁOŚĆ W METRACH", "Kontrolowane przez hosta, zobacz {key:Ghost-Free-Cam/enable-ghost-free-cam}. Jak daleko wolna kamera ducha może zwiadować od żywego gracza, którego aktualnie obserwuje, zanim zostanie ściągnięta z powrotem, jak łańcuch tej długości. Całkowicie ignorowane, gdy {key:Ghost-Free-Cam/unlimited-range} jest włączone."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("MAKS. MESAFE (METRE)", "Host tarafından kontrol edilir, bkz. {key:Ghost-Free-Cam/enable-ghost-free-cam}. Bir hayaletin serbest kamerası, şu anda izlediği canlı oyuncudan geri çekilmeden önce bu uzunlukta bir zincir gibi ne kadar uzağa keşfe çıkabilir. {key:Ghost-Free-Cam/unlimited-range} açıkken tamamen yok sayılır."),
            });

            Add("unlimited-range", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("UNLIMITED RANGE", "Host-controlled, see {key:Ghost-Free-Cam/enable-ghost-free-cam}. Removes {key:Ghost-Free-Cam/max-distance-meters}' leash entirely, letting ghosts free-cam anywhere on the map. Off by default, since the leash is what keeps this mechanic from being overpowered."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("PORTÉE ILLIMITÉE", "Contrôlé par l'hôte, voir {key:Ghost-Free-Cam/enable-ghost-free-cam}. Supprime entièrement la laisse de {key:Ghost-Free-Cam/max-distance-meters}, permettant aux fantômes de se déplacer librement partout sur la carte. Désactivé par défaut, car c'est la laisse qui empêche ce mécanisme d'être surpuissant."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("RAGGIO ILLIMITATO", "Controllato dall'host, vedi {key:Ghost-Free-Cam/enable-ghost-free-cam}. Rimuove completamente il guinzaglio di {key:Ghost-Free-Cam/max-distance-meters}, permettendo ai fantasmi di muoversi liberamente ovunque sulla mappa. Disattivato per impostazione predefinita, poiché il guinzaglio è ciò che impedisce a questa meccanica di essere squilibrata."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("UNBEGRENZTE REICHWEITE", "Vom Host gesteuert, siehe {key:Ghost-Free-Cam/enable-ghost-free-cam}. Entfernt die Leine von {key:Ghost-Free-Cam/max-distance-meters} komplett und lässt Geister überall auf der Karte frei fliegen. Standardmäßig deaktiviert, da die Leine diesen Mechanismus vor Überlegenheit bewahrt."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("ALCANCE ILIMITADO", "Controlado por el anfitrión, ver {key:Ghost-Free-Cam/enable-ghost-free-cam}. Elimina por completo la correa de {key:Ghost-Free-Cam/max-distance-meters}, permitiendo a los fantasmas volar libremente por cualquier parte del mapa. Desactivado por defecto, ya que la correa es lo que evita que esta mecánica sea desequilibrada."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("ALCANCE ILIMITADO", "Controlado por el anfitrión, ver {key:Ghost-Free-Cam/enable-ghost-free-cam}. Elimina por completo la correa de {key:Ghost-Free-Cam/max-distance-meters}, permitiendo a los fantasmas volar libremente por cualquier parte del mapa. Desactivado por defecto, ya que la correa es lo que evita que esta mecánica sea desequilibrada."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("ALCANCE ILIMITADO", "Controlado pelo anfitrião, veja {key:Ghost-Free-Cam/enable-ghost-free-cam}. Remove completamente a coleira de {key:Ghost-Free-Cam/max-distance-meters}, permitindo que fantasmas voem livremente por qualquer lugar do mapa. Desativado por padrão, já que a coleira é o que impede essa mecânica de ficar desequilibrada."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("НЕОГРАНИЧЕННЫЙ РАДИУС", "Управляется хостом, см. {key:Ghost-Free-Cam/enable-ghost-free-cam}. Полностью убирает привязь {key:Ghost-Free-Cam/max-distance-meters}, позволяя призракам летать где угодно по карте. Выключено по умолчанию, поскольку именно привязь удерживает эту механику от чрезмерной мощи."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("НЕОБМЕЖЕНИЙ РАДІУС", "Керується хостом, див. {key:Ghost-Free-Cam/enable-ghost-free-cam}. Повністю прибирає прив'язь {key:Ghost-Free-Cam/max-distance-meters}, дозволяючи привидам літати будь-де на карті. Вимкнено за замовчуванням, оскільки саме прив'язь утримує цю механіку від надмірної потужності."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("无限范围", "由房主控制，参见 {key:Ghost-Free-Cam/enable-ghost-free-cam}。完全移除 {key:Ghost-Free-Cam/max-distance-meters} 的限制链，让幽灵可以在地图上任意位置自由飞行。默认关闭，因为正是这条限制链让此机制不至于过于强大。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("無限範圍", "由房主控制，參見 {key:Ghost-Free-Cam/enable-ghost-free-cam}。完全移除 {key:Ghost-Free-Cam/max-distance-meters} 的限制鏈，讓幽靈可以在地圖上任意位置自由飛行。預設關閉，因為正是這條限制鏈讓此機制不至於過於強大。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("無制限の範囲", "ホスト制御、{key:Ghost-Free-Cam/enable-ghost-free-cam}を参照。{key:Ghost-Free-Cam/max-distance-meters}の鎖を完全に取り除き、ゴーストがマップ上のどこでも自由に飛べるようにします。この鎖がこの機能の強すぎる状態を防いでいるため、デフォルトはオフです。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("무제한 범위", "호스트가 제어함, {key:Ghost-Free-Cam/enable-ghost-free-cam} 참조. {key:Ghost-Free-Cam/max-distance-meters}의 사슬을 완전히 제거하여 고스트가 맵 어디든 자유롭게 비행할 수 있게 합니다. 사슬이 이 메커니즘의 과도한 강력함을 막아주므로 기본적으로 꺼져 있습니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("NIEOGRANICZONY ZASIĘG", "Kontrolowane przez hosta, zobacz {key:Ghost-Free-Cam/enable-ghost-free-cam}. Całkowicie usuwa smycz {key:Ghost-Free-Cam/max-distance-meters}, pozwalając duchom swobodnie latać po całej mapie. Domyślnie wyłączone, ponieważ to smycz utrzymuje ten mechanizm przed nadmierną siłą."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("SINIRSIZ MENZİL", "Host tarafından kontrol edilir, bkz. {key:Ghost-Free-Cam/enable-ghost-free-cam}. {key:Ghost-Free-Cam/max-distance-meters}'ın zincirini tamamen kaldırır ve hayaletlerin haritanın herhangi bir yerinde serbestçe uçmasına izin verir. Bu mekaniği aşırı güçlü olmaktan alıkoyan şey zincir olduğu için varsayılan olarak kapalıdır."),
            });

            Add("toggle-key", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("TOGGLE KEY", "Purely local. Key that toggles free-fly camera mode on/off while you're dead and spectating; each player binds their own. Only does anything while {key:Ghost-Free-Cam/enable-ghost-free-cam} ends up effectively on (see that setting for how that's decided)."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("TOUCHE DE BASCULE", "Purement local. Touche qui active/désactive le mode caméra libre pendant que vous êtes mort et en train d'observer ; chaque joueur configure la sienne. N'a d'effet que si {key:Ghost-Free-Cam/enable-ghost-free-cam} est effectivement activé (voir ce réglage pour savoir comment cela est décidé)."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("TASTO DI ATTIVAZIONE", "Puramente locale. Tasto che attiva/disattiva la modalità telecamera libera mentre sei morto e stai osservando; ogni giocatore imposta il proprio. Ha effetto solo quando {key:Ghost-Free-Cam/enable-ghost-free-cam} risulta effettivamente attivo (vedi quell'impostazione per come viene deciso)."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("UMSCHALTTASTE", "Rein lokal. Taste, die den Freiflugkamera-Modus ein-/ausschaltet, während du tot bist und zuschaust; jeder Spieler bindet seine eigene. Hat nur eine Wirkung, wenn {key:Ghost-Free-Cam/enable-ghost-free-cam} effektiv aktiv ist (siehe diese Einstellung für die Entscheidung darüber)."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("TECLA DE ALTERNAR", "Puramente local. Tecla que activa/desactiva el modo de cámara libre mientras estás muerto y observando; cada jugador configura la suya propia. Solo hace algo mientras {key:Ghost-Free-Cam/enable-ghost-free-cam} termine estando efectivamente activado (ver ese ajuste para saber cómo se decide)."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("TECLA DE ALTERNAR", "Puramente local. Tecla que activa/desactiva el modo de cámara libre mientras estás muerto y observando; cada jugador configura la suya propia. Solo hace algo mientras {key:Ghost-Free-Cam/enable-ghost-free-cam} termine estando efectivamente activado (ver ese ajuste para saber cómo se decide)."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("TECLA DE ALTERNÂNCIA", "Puramente local. Tecla que ativa/desativa o modo de câmera livre enquanto você está morto e observando; cada jogador vincula a sua própria. Só faz efeito enquanto {key:Ghost-Free-Cam/enable-ghost-free-cam} acaba efetivamente ativado (veja essa configuração para saber como isso é decidido)."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("КЛАВИША ПЕРЕКЛЮЧЕНИЯ", "Полностью локально. Клавиша, включающая/выключающая режим свободного полёта камеры, пока вы мертвы и наблюдаете; каждый игрок назначает свою. Работает, только если {key:Ghost-Free-Cam/enable-ghost-free-cam} в итоге включён (см. эту настройку, чтобы узнать, как это решается)."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("КЛАВІША ПЕРЕМИКАННЯ", "Повністю локально. Клавіша, яка вмикає/вимикає режим вільного польоту камери, поки ви мертві та спостерігаєте; кожен гравець призначає свою. Працює лише якщо {key:Ghost-Free-Cam/enable-ghost-free-cam} зрештою увімкнено (див. це налаштування, щоб дізнатися, як це вирішується)."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("切换键", "纯本地设置。在你死亡并旁观时用于开关自由飞行摄像机模式的按键；每位玩家各自绑定自己的按键。仅当 {key:Ghost-Free-Cam/enable-ghost-free-cam} 实际生效为开启状态时才起作用（该设置如何决定生效方式请参见该项）。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("切換鍵", "純本地設定。在你死亡並旁觀時用於開關自由飛行攝影機模式的按鍵；每位玩家各自綁定自己的按鍵。僅當 {key:Ghost-Free-Cam/enable-ghost-free-cam} 實際生效為開啟狀態時才起作用（該設定如何決定生效方式請參見該項）。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("切り替えキー", "完全にローカルな設定です。死亡して観戦している間、フリーフライトカメラモードのオン/オフを切り替えるキーで、各プレイヤーが自分用に割り当てます。{key:Ghost-Free-Cam/enable-ghost-free-cam}が実質的に有効になっている場合にのみ機能します（決定方法はその設定を参照）。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("전환 키", "완전히 로컬 설정입니다. 사망하여 관전하는 동안 자유 비행 카메라 모드를 켜고 끄는 키이며, 각 플레이어가 자신의 키를 바인딩합니다. {key:Ghost-Free-Cam/enable-ghost-free-cam}이 실제로 켜진 상태일 때만 작동합니다(어떻게 결정되는지는 해당 설정 참조)."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("KLAWISZ PRZEŁĄCZANIA", "Wyłącznie lokalne. Klawisz, który przełącza tryb swobodnej kamery podczas gdy jesteś martwy i obserwujesz; każdy gracz przypisuje swój własny. Działa tylko wtedy, gdy {key:Ghost-Free-Cam/enable-ghost-free-cam} jest faktycznie włączone (zobacz to ustawienie, aby dowiedzieć się, jak to jest decydowane)."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("AÇMA/KAPAMA TUŞU", "Tamamen yerel. Öldüğünüzde ve izlerken serbest uçuş kamera modunu açıp kapatan tuş; her oyuncu kendi tuşunu atar. Yalnızca {key:Ghost-Free-Cam/enable-ghost-free-cam} etkin biçimde açık olduğunda bir işe yarar (bunun nasıl belirlendiğini görmek için o ayara bakın)."),
            });

            Add("move-speed-meters-per-second", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("MOVE SPEED METERS PER SECOND", "Purely local. How fast the free camera flies. PEAK's own built-in dev free-camera controller (reused for the first pass of this feature) turned out to feel unusably slow in practice, so this mod drives its own movement directly in real-world meters/second instead of relying on that controller's tuning."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("VITESSE DE DÉPLACEMENT EN MÈTRES PAR SECONDE", "Purement local. À quelle vitesse la caméra libre vole. Le contrôleur de caméra libre de développement intégré à PEAK (réutilisé pour la première version de cette fonctionnalité) s'est révélé inutilisablement lent en pratique, donc ce mod gère son propre mouvement directement en mètres par seconde réels plutôt que de dépendre du réglage de ce contrôleur."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("VELOCITÀ DI MOVIMENTO IN METRI AL SECONDO", "Puramente locale. Quanto velocemente vola la telecamera libera. Il controller di telecamera libera per sviluppatori integrato in PEAK (riutilizzato per la prima versione di questa funzionalità) si è rivelato inutilizzabilmente lento nella pratica, quindi questa mod gestisce il proprio movimento direttamente in metri al secondo reali invece di affidarsi alla regolazione di quel controller."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("BEWEGUNGSGESCHWINDIGKEIT IN METERN PRO SEKUNDE", "Rein lokal. Wie schnell die Freikamera fliegt. PEAKs eigener eingebauter Entwickler-Freikamera-Controller (für die erste Version dieses Features wiederverwendet) erwies sich in der Praxis als unbrauchbar langsam, daher steuert dieser Mod seine eigene Bewegung direkt in realen Metern pro Sekunde, statt sich auf die Abstimmung dieses Controllers zu verlassen."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("VELOCIDAD DE MOVIMIENTO EN METROS POR SEGUNDO", "Puramente local. Qué tan rápido vuela la cámara libre. El controlador de cámara libre de desarrollo integrado de PEAK (reutilizado para la primera versión de esta función) resultó ser inutilizablemente lento en la práctica, así que este mod gestiona su propio movimiento directamente en metros por segundo reales en lugar de depender del ajuste de ese controlador."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("VELOCIDAD DE MOVIMIENTO EN METROS POR SEGUNDO", "Puramente local. Qué tan rápido vuela la cámara libre. El controlador de cámara libre de desarrollo integrado de PEAK (reutilizado para la primera versión de esta función) resultó ser inutilizablemente lento en la práctica, así que este mod gestiona su propio movimiento directamente en metros por segundo reales en lugar de depender del ajuste de ese controlador."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("VELOCIDADE DE MOVIMENTO EM METROS POR SEGUNDO", "Puramente local. Quão rápido a câmera livre voa. O controlador de câmera livre de desenvolvedor integrado do PEAK (reaproveitado para a primeira versão deste recurso) se mostrou inutilizavelmente lento na prática, então este mod controla seu próprio movimento diretamente em metros por segundo reais, em vez de depender do ajuste desse controlador."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("СКОРОСТЬ ДВИЖЕНИЯ В МЕТРАХ В СЕКУНДУ", "Полностью локально. Насколько быстро летает свободная камера. Встроенный в PEAK контроллер свободной камеры для разработчиков (использованный в первой версии этой функции) оказался на практике непригодно медленным, поэтому этот мод управляет своим движением напрямую в реальных метрах в секунду, а не полагается на настройки того контроллера."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("ШВИДКІСТЬ РУХУ В МЕТРАХ НА СЕКУНДУ", "Повністю локально. Наскільки швидко літає вільна камера. Вбудований у PEAK контролер вільної камери для розробників (використаний у першій версії цієї функції) на практиці виявився непридатно повільним, тому цей мод керує своїм рухом напряму в реальних метрах на секунду, а не покладається на налаштування того контролера."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("移动速度（米/秒）", "纯本地设置。自由摄像机的飞行速度。PEAK 自带的内置开发者自由摄像机控制器（该功能首个版本曾重用过）在实际使用中慢得几乎不可用，因此本模组直接以现实世界的米/秒来驱动自身的移动，而不依赖该控制器的调校。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("移動速度（公尺/秒）", "純本地設定。自由攝影機的飛行速度。PEAK 自帶的內建開發者自由攝影機控制器（該功能首個版本曾重用過）在實際使用中慢得幾乎不可用，因此本模組直接以現實世界的公尺/秒來驅動自身的移動，而不依賴該控制器的調校。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("移動速度（メートル毎秒）", "完全にローカルな設定です。フリーカメラの飛行速度。PEAK自体に組み込まれた開発者用フリーカメラコントローラー（この機能の最初のバージョンで再利用）は実際には使い物にならないほど遅かったため、このMODはそのコントローラーの調整に頼らず、現実の秒速メートルで直接自身の移動を制御します。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("이동 속도(초당 미터)", "완전히 로컬 설정입니다. 프리캠이 비행하는 속도입니다. PEAK 자체에 내장된 개발자용 프리카메라 컨트롤러(이 기능의 첫 버전에서 재사용됨)는 실제로 사용하기 힘들 정도로 느린 것으로 드러나, 이 모드는 해당 컨트롤러의 조정 값에 의존하는 대신 실제 초당 미터 단위로 직접 이동을 제어합니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("PRĘDKOŚĆ RUCHU W METRACH NA SEKUNDĘ", "Wyłącznie lokalne. Jak szybko lata wolna kamera. Wbudowany w PEAK deweloperski kontroler wolnej kamery (ponownie użyty w pierwszej wersji tej funkcji) okazał się w praktyce nieużywalnie wolny, więc ten mod steruje własnym ruchem bezpośrednio w rzeczywistych metrach na sekundę zamiast polegać na dostrojeniu tego kontrolera."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("HAREKET HIZI (SANİYEDE METRE)", "Tamamen yerel. Serbest kameranın ne kadar hızlı uçtuğu. PEAK'in kendi yerleşik geliştirici serbest kamera denetleyicisi (bu özelliğin ilk sürümü için yeniden kullanılmıştı) pratikte kullanılamayacak kadar yavaş çıktı; bu yüzden bu mod, o denetleyicinin ayarına güvenmek yerine kendi hareketini doğrudan gerçek dünya saniye/metre cinsinden yönetir."),
            });

            Add("sprint-multiplier", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("SPRINT MULTIPLIER", "Purely local. Speed multiplier while holding Left Shift."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("MULTIPLICATEUR DE SPRINT", "Purement local. Multiplicateur de vitesse en maintenant Left Shift."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("MOLTIPLICATORE SCATTO", "Puramente locale. Moltiplicatore di velocità tenendo premuto Left Shift."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("SPRINT-MULTIPLIKATOR", "Rein lokal. Geschwindigkeitsmultiplikator beim Halten von Left Shift."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("MULTIPLICADOR DE CARRERA", "Puramente local. Multiplicador de velocidad al mantener pulsado Left Shift."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("MULTIPLICADOR DE CARRERA", "Puramente local. Multiplicador de velocidad al mantener presionado Left Shift."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("MULTIPLICADOR DE CORRIDA", "Puramente local. Multiplicador de velocidade ao segurar Left Shift."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("МНОЖИТЕЛЬ УСКОРЕНИЯ", "Полностью локально. Множитель скорости при удержании Left Shift."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("МНОЖНИК ПРИСКОРЕННЯ", "Повністю локально. Множник швидкості при утриманні Left Shift."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("疾跑倍率", "纯本地设置。按住 Left Shift 时的速度倍率。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("疾跑倍率", "純本地設定。按住 Left Shift 時的速度倍率。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("ダッシュ倍率", "完全にローカルな設定です。Left Shiftを押している間の速度倍率。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("질주 배율", "완전히 로컬 설정입니다. Left Shift를 누르고 있는 동안의 속도 배율입니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("MNOŻNIK SPRINTU", "Wyłącznie lokalne. Mnożnik prędkości podczas przytrzymywania Left Shift."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("KOŞU ÇARPANI", "Tamamen yerel. Left Shift basılı tutulurken hız çarpanı."),
            });

            Add("show-crosshair", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("SHOW CROSSHAIR", "Purely local. Shows a small reticle at the center of the screen while free-cam is engaged, so you have something to aim regular pings at (spectate mode otherwise has no crosshair at all)."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("AFFICHER LE RÉTICULE", "Purement local. Affiche un petit réticule au centre de l'écran lorsque la caméra libre est active, pour avoir quelque chose à viser avec les pings normaux (le mode spectateur n'a sinon aucun réticule)."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("MOSTRA MIRINO", "Puramente locale. Mostra un piccolo mirino al centro dello schermo quando la telecamera libera è attiva, così hai qualcosa su cui mirare i ping normali (la modalità spettatore altrimenti non ha alcun mirino)."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("FADENKREUZ ANZEIGEN", "Rein lokal. Zeigt ein kleines Fadenkreuz in der Bildschirmmitte, während die Freikamera aktiv ist, damit du etwas hast, worauf du normale Pings zielen kannst (der Zuschauermodus hat sonst überhaupt kein Fadenkreuz)."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("MOSTRAR MIRA", "Puramente local. Muestra una pequeña mira en el centro de la pantalla mientras la cámara libre está activa, para tener algo a lo que apuntar con los pings normales (el modo espectador de otro modo no tiene mira alguna)."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("MOSTRAR MIRA", "Puramente local. Muestra una pequeña mira en el centro de la pantalla mientras la cámara libre está activa, para tener algo a lo que apuntar con los pings normales (el modo espectador de otro modo no tiene mira alguna)."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("MOSTRAR MIRA", "Puramente local. Mostra uma pequena mira no centro da tela enquanto a câmera livre está ativa, para que você tenha algo para mirar com pings normais (o modo espectador não tem mira alguma de outra forma)."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("ПОКАЗЫВАТЬ ПРИЦЕЛ", "Полностью локально. Показывает небольшой прицел в центре экрана, пока активна свободная камера, чтобы было куда наводить обычные пинги (иначе в режиме наблюдателя прицела нет вообще)."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("ПОКАЗУВАТИ ПРИЦІЛ", "Повністю локально. Показує невеликий приціл у центрі екрана, поки активна вільна камера, щоб було куди наводити звичайні пінги (інакше в режимі спостерігача прицілу немає взагалі)."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("显示准星", "纯本地设置。在自由摄像机启用时于屏幕中央显示一个小准星，方便你瞄准以进行普通呼喊（否则旁观模式完全没有准星）。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("顯示準星", "純本地設定。在自由攝影機啟用時於螢幕中央顯示一個小準星，方便你瞄準以進行普通呼喊（否則旁觀模式完全沒有準星）。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("照準を表示", "完全にローカルな設定です。フリーカメラが有効な間、画面中央に小さな照準を表示し、通常のピンを狙えるようにします（観戦モードには本来まったく照準がありません）。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("조준점 표시", "완전히 로컬 설정입니다. 프리캠이 작동 중일 때 화면 중앙에 작은 조준점을 표시하여 일반 핑을 조준할 대상이 생기게 합니다(그렇지 않으면 관전 모드에는 조준점이 전혀 없습니다)."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("POKAZUJ CELOWNIK", "Wyłącznie lokalne. Pokazuje mały celownik na środku ekranu, gdy wolna kamera jest aktywna, dzięki czemu masz w co celować zwykłymi pingami (tryb obserwatora inaczej nie ma żadnego celownika)."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("NİŞANGAHI GÖSTER", "Tamamen yerel. Serbest kamera etkinken ekranın ortasında küçük bir nişangah gösterir, böylece normal pingleri hedefleyebileceğiniz bir şey olur (izleyici modunda aksi halde hiç nişangah yoktur)."),
            });

            Add("show-key-hint", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("SHOW KEY HINT", "Purely local. Shows a key badge + short label near vanilla's own \"you are a ghost\" panel reminding you which key toggles free-cam (and whether it'll engage or disengage), since vanilla's UI never mentions this mod's keybind at all."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("AFFICHER L'INDICE DE TOUCHE", "Purement local. Affiche un badge de touche + une courte étiquette près du panneau « vous êtes un fantôme » du jeu de base pour rappeler quelle touche bascule la caméra libre (et si elle va s'activer ou se désactiver), puisque l'interface de base ne mentionne jamais la touche de ce mod."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("MOSTRA SUGGERIMENTO TASTO", "Puramente locale. Mostra un badge del tasto + una breve etichetta vicino al pannello base \"sei un fantasma\" per ricordarti quale tasto attiva la telecamera libera (e se si attiverà o disattiverà), poiché l'interfaccia base non menziona mai il tasto di questa mod."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("TASTENHINWEIS ANZEIGEN", "Rein lokal. Zeigt ein Tasten-Badge + eine kurze Beschriftung neben dem originalen „du bist ein Geist“-Panel, das dich daran erinnert, welche Taste die Freikamera umschaltet (und ob sie sich aktiviert oder deaktiviert), da die Original-UI die Tastenbelegung dieses Mods nie erwähnt."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("MOSTRAR INDICACIÓN DE TECLA", "Puramente local. Muestra una insignia de tecla + una etiqueta corta cerca del panel original «eres un fantasma» que te recuerda qué tecla alterna la cámara libre (y si se activará o desactivará), ya que la interfaz original nunca menciona el atajo de este mod."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("MOSTRAR INDICACIÓN DE TECLA", "Puramente local. Muestra una insignia de tecla + una etiqueta corta cerca del panel original «eres un fantasma» que te recuerda qué tecla alterna la cámara libre (y si se activará o desactivará), ya que la interfaz original nunca menciona el atajo de este mod."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("MOSTRAR DICA DE TECLA", "Puramente local. Mostra um selo de tecla + um rótulo curto perto do painel original \"você é um fantasma\" lembrando qual tecla alterna a câmera livre (e se ela vai ativar ou desativar), já que a interface original nunca menciona o atalho deste mod."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("ПОКАЗЫВАТЬ ПОДСКАЗКУ КЛАВИШИ", "Полностью локально. Показывает значок клавиши + короткую подпись рядом с оригинальной панелью «вы призрак», напоминая, какая клавиша переключает свободную камеру (и включится она или выключится), поскольку оригинальный интерфейс никогда не упоминает клавишу этого мода."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("ПОКАЗУВАТИ ПІДКАЗКУ КЛАВІШІ", "Повністю локально. Показує значок клавіші + короткий підпис біля оригінальної панелі «ви привид», нагадуючи, яка клавіша перемикає вільну камеру (і чи увімкнеться вона, чи вимкнеться), оскільки оригінальний інтерфейс ніколи не згадує клавішу цього мода."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("显示按键提示", "纯本地设置。在原版“你是幽灵”面板附近显示一个按键徽标和简短标签，提醒你哪个按键用于切换自由摄像机（以及是启用还是关闭），因为原版界面完全不会提及本模组的按键绑定。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("顯示按鍵提示", "純本地設定。在原版「你是幽靈」面板附近顯示一個按鍵徽標和簡短標籤，提醒你哪個按鍵用於切換自由攝影機（以及是啟用還是關閉），因為原版介面完全不會提及本模組的按鍵綁定。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("キーヒントを表示", "完全にローカルな設定です。バニラの「あなたはゴーストです」パネルの近くにキーバッジと短いラベルを表示し、フリーカメラを切り替えるキー（オンになるかオフになるか）を思い出させます。バニラのUIはこのMODのキー割り当てについて一切触れないためです。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("키 힌트 표시", "완전히 로컬 설정입니다. 바닐라의 \"당신은 유령입니다\" 패널 근처에 키 배지와 짧은 라벨을 표시하여 프리캠을 전환하는 키(그리고 켜질지 꺼질지)를 알려줍니다. 바닐라 UI는 이 모드의 키 바인딩을 전혀 언급하지 않기 때문입니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("POKAZUJ PODPOWIEDŹ KLAWISZA", "Wyłącznie lokalne. Pokazuje odznakę klawisza + krótką etykietę obok oryginalnego panelu „jesteś duchem”, przypominając, który klawisz przełącza wolną kamerę (i czy się włączy, czy wyłączy), ponieważ oryginalny interfejs nigdy nie wspomina o skrócie klawiszowym tego moda."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("TUŞ İPUCUNU GÖSTER", "Tamamen yerel. Orijinal \"bir hayaletsiniz\" panelinin yanında, serbest kamerayı hangi tuşun açıp kapattığını (ve açılacağını mı kapanacağını mı) hatırlatan bir tuş rozeti + kısa etiket gösterir; çünkü orijinal arayüz bu modun tuş atamasından hiç bahsetmez."),
            });

            Add("hide-all-ghosts", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("HIDE ALL GHOSTS", "Purely local. Hides every dead player's ghost body from your own view entirely. Doesn't affect anyone else, and doesn't affect your own ability to spectate/free-cam while dead yourself."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("MASQUER TOUS LES FANTÔMES", "Purement local. Masque entièrement le corps fantôme de chaque joueur mort de votre propre vue. N'affecte personne d'autre, et n'affecte pas votre propre capacité à observer/utiliser la caméra libre si vous êtes vous-même mort."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("NASCONDI TUTTI I FANTASMI", "Puramente locale. Nasconde completamente il corpo fantasma di ogni giocatore morto dalla tua visuale. Non influisce su nessun altro, e non influisce sulla tua capacità di osservare/usare la telecamera libera se sei tu stesso morto."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("ALLE GEISTER AUSBLENDEN", "Rein lokal. Blendet den Geisterkörper jedes toten Spielers komplett aus deiner eigenen Sicht aus. Betrifft niemand anderen und beeinträchtigt nicht deine eigene Fähigkeit, zuzuschauen/die Freikamera zu nutzen, wenn du selbst tot bist."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("OCULTAR TODOS LOS FANTASMAS", "Puramente local. Oculta por completo el cuerpo fantasma de cada jugador muerto de tu propia vista. No afecta a nadie más, y no afecta a tu propia capacidad de observar/usar la cámara libre si tú mismo estás muerto."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("OCULTAR TODOS LOS FANTASMAS", "Puramente local. Oculta por completo el cuerpo fantasma de cada jugador muerto de tu propia vista. No afecta a nadie más, y no afecta a tu propia capacidad de observar/usar la cámara libre si tú mismo estás muerto."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("OCULTAR TODOS OS FANTASMAS", "Puramente local. Oculta completamente o corpo fantasma de cada jogador morto da sua própria visão. Não afeta mais ninguém, e não afeta sua própria capacidade de observar/usar a câmera livre caso você mesmo esteja morto."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("СКРЫТЬ ВСЕХ ПРИЗРАКОВ", "Полностью локально. Полностью скрывает призрачное тело каждого погибшего игрока из вашего собственного обзора. Не влияет ни на кого другого и не влияет на вашу собственную возможность наблюдать/использовать свободную камеру, если вы сами погибли."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("СХОВАТИ ВСІХ ПРИВИДІВ", "Повністю локально. Повністю приховує примарне тіло кожного загиблого гравця з вашого власного огляду. Не впливає на когось іншого і не впливає на вашу власну можливість спостерігати/використовувати вільну камеру, якщо ви самі загинули."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("隐藏所有幽灵", "纯本地设置。在你自己的视角中完全隐藏每个死亡玩家的幽灵身影。不会影响其他任何人，也不会影响你自己死亡时旁观/使用自由摄像机的能力。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("隱藏所有幽靈", "純本地設定。在你自己的視角中完全隱藏每個死亡玩家的幽靈身影。不會影響其他任何人，也不會影響你自己死亡時旁觀/使用自由攝影機的能力。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("すべてのゴーストを非表示", "完全にローカルな設定です。すべての死亡プレイヤーのゴースト姿を自分の視界から完全に非表示にします。他の誰にも影響せず、自分自身が死亡した際の観戦/フリーカメラ利用能力にも影響しません。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("모든 유령 숨기기", "완전히 로컬 설정입니다. 모든 사망한 플레이어의 유령 모습을 자신의 화면에서 완전히 숨깁니다. 다른 누구에게도 영향을 주지 않으며, 자신이 사망했을 때 관전/프리캠을 사용하는 능력에도 영향을 주지 않습니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("UKRYJ WSZYSTKIE DUCHY", "Wyłącznie lokalne. Całkowicie ukrywa ciało ducha każdego martwego gracza z twojego własnego widoku. Nie wpływa na nikogo innego i nie wpływa na twoją własną możliwość obserwowania/używania wolnej kamery, gdy sam jesteś martwy."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("TÜM HAYALETLERİ GİZLE", "Tamamen yerel. Her ölü oyuncunun hayalet bedenini kendi görüşünüzden tamamen gizler. Başka kimseyi etkilemez ve siz kendiniz öldüğünüzde izleme/serbest kamera kullanma yeteneğinizi etkilemez."),
            });
        }
    }
}
