using System.Collections.Generic;

namespace SenseOfDirection.Ui.Localization.Config
{
    /// <summary>Localized names/descriptions for every "Item-Pings" section config entry.</summary>
    internal static class ItemPingsConfigLocalization
    {
        internal static void Register(ConfigLocalizationTable.Registry registry)
        {
            void Add(string key, Dictionary<LocalizedText.Language, ConfigLocalizationEntry> table) =>
                registry.Add("Item-Pings", key, table);

            Add("enable-item-pings", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("ENABLE ITEM PINGS", "Highlight nearby items/luggage when you ping near them, with a name and distance label, as a native replacement for the (now confirmed broken against the current game version) memiczny-PingItems mod."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("ACTIVER LES PINGS D'OBJETS", "Met en surbrillance les objets/bagages proches lorsque vous les pingez, avec un nom et une distance, comme remplacement natif du mod memiczny-PingItems (désormais confirmé cassé avec la version actuelle du jeu)."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("ATTIVA PING OGGETTI", "Evidenzia oggetti/bagagli vicini quando li segnali con un ping, mostrando nome e distanza, come sostituto nativo del mod memiczny-PingItems (ora confermato non funzionante con la versione attuale del gioco)."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("GEGENSTANDS-PINGS AKTIVIEREN", "Hebt nahe Gegenstände/Gepäck hervor, wenn du sie anpingst, mit Name und Entfernung, als nativer Ersatz für das (inzwischen bestätigt mit der aktuellen Spielversion kaputte) Mod memiczny-PingItems."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("ACTIVAR PINGS DE OBJETOS", "Resalta objetos/equipaje cercanos al hacerles ping, con un nombre y una etiqueta de distancia, como reemplazo nativo del mod memiczny-PingItems (ahora confirmado que no funciona con la versión actual del juego)."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("ACTIVAR PINGS DE OBJETOS", "Resalta objetos/equipaje cercanos al hacerles ping, con un nombre y una etiqueta de distancia, como reemplazo nativo del mod memiczny-PingItems (ahora confirmado que no funciona con la versión actual del juego)."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("ATIVAR PINGS DE ITENS", "Destaca itens/bagagens próximos quando você os pinga, com nome e distância, como substituto nativo do mod memiczny-PingItems (agora confirmado quebrado na versão atual do jogo)."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("ВКЛЮЧИТЬ ПИНГИ ПРЕДМЕТОВ", "Подсвечивает ближайшие предметы/багаж при пинге рядом с ними, показывая название и расстояние - как встроенная замена мода memiczny-PingItems (который, как подтверждено, сломан в текущей версии игры)."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("УВІМКНУТИ ПІНГИ ПРЕДМЕТІВ", "Підсвічує найближчі предмети/багаж під час пінгу поруч із ними, показуючи назву та відстань - як вбудована заміна мода memiczny-PingItems (який, як підтверджено, не працює в поточній версії гри)."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("启用物品呼喊", "当你在附近呼喊时高亮显示物品/行李箱，并显示名称和距离，作为 memiczny-PingItems 模组（现已确认在当前游戏版本中失效）的原生替代方案。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("啟用物品呼喊", "當你在附近呼喊時高亮顯示物品/行李箱，並顯示名稱和距離，作為 memiczny-PingItems 模組（現已確認在目前遊戲版本中失效）的原生替代方案。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("アイテムピンを有効化", "近くのアイテムや荷物にピンを送ると、名前と距離を添えてハイライト表示します。現在のゲームバージョンで動作しないことが確認された memiczny-PingItems MOD のネイティブな代替機能です。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("아이템 핑 활성화", "근처의 아이템/수하물에 핑을 보내면 이름과 거리를 표시하며 강조합니다. 현재 게임 버전에서 작동하지 않는 것으로 확인된 memiczny-PingItems 모드의 네이티브 대체 기능입니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("WŁĄCZ PINGI PRZEDMIOTÓW", "Podświetla pobliskie przedmioty/bagaże po ich zapingowaniu, pokazując nazwę i odległość, jako natywny zamiennik moda memiczny-PingItems (potwierdzono, że nie działa z obecną wersją gry)."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("EŞYA PİNGLERİNİ ETKİNLEŞTİR", "Yakındaki eşyaları/bagajları pingleyince ad ve mesafe etiketiyle vurgular; mevcut oyun sürümünde bozuk olduğu doğrulanan memiczny-PingItems modunun yerel bir alternatifidir."),
            });

            Add("duration-seconds", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("DURATION SECONDS", "How long an item/luggage highlight stays visible before fading out (ends early regardless if the item is picked up or the luggage is opened)."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("DURÉE EN SECONDES", "Combien de temps une surbrillance d'objet/bagage reste visible avant de s'estomper (se termine plus tôt si l'objet est ramassé ou le bagage ouvert)."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("DURATA IN SECONDI", "Per quanto tempo l'evidenziazione di un oggetto/bagaglio resta visibile prima di svanire (termina prima se l'oggetto viene raccolto o il bagaglio aperto)."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("DAUER IN SEKUNDEN", "Wie lange die Hervorhebung eines Gegenstands/Gepäckstücks sichtbar bleibt, bevor sie ausblendet (endet früher, falls der Gegenstand aufgehoben oder das Gepäck geöffnet wird)."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("DURACIÓN EN SEGUNDOS", "Cuánto tiempo permanece visible el resalte de un objeto/equipaje antes de desvanecerse (termina antes si el objeto se recoge o el equipaje se abre)."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("DURACIÓN EN SEGUNDOS", "Cuánto tiempo permanece visible el resalte de un objeto/equipaje antes de desvanecerse (termina antes si el objeto se recoge o el equipaje se abre)."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("DURAÇÃO EM SEGUNDOS", "Por quanto tempo o destaque de um item/bagagem permanece visível antes de desaparecer (termina antes se o item for pego ou a bagagem for aberta)."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("ДЛИТЕЛЬНОСТЬ В СЕКУНДАХ", "Как долго подсветка предмета/багажа остаётся видимой перед исчезновением (заканчивается раньше, если предмет подобран или багаж открыт)."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("ТРИВАЛІСТЬ У СЕКУНДАХ", "Як довго підсвітка предмета/багажу залишається видимою перед зникненням (завершується раніше, якщо предмет підібрано або багаж відкрито)."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("持续秒数", "物品/行李箱高亮效果在淡出前保持可见的时间（如果物品被拾取或行李箱被打开，则会提前结束）。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("持續秒數", "物品/行李箱高亮效果在淡出前保持可見的時間（如果物品被撿起或行李箱被打開，則會提前結束）。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("表示時間（秒）", "アイテム/荷物のハイライトがフェードアウトするまで表示され続ける時間です（アイテムが拾われるか荷物が開けられると早めに終了します）。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("지속 시간(초)", "아이템/수하물 강조 표시가 서서히 사라지기 전까지 유지되는 시간입니다 (아이템을 줍거나 수하물을 열면 더 일찍 종료됩니다)."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("CZAS TRWANIA W SEKUNDACH", "Jak długo podświetlenie przedmiotu/bagażu pozostaje widoczne przed zanikiem (kończy się wcześniej, jeśli przedmiot zostanie podniesiony lub bagaż otwarty)."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("SÜRE (SANİYE)", "Bir eşya/bagaj vurgusunun solmadan önce ne kadar süre görünür kalacağı (eşya alınırsa veya bagaj açılırsa daha erken sona erer)."),
            });

            Add("enable-grouping", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("ENABLE GROUPING", "Group multiple nearby items of the same kind into a single highlight showing a count (e.g. \"3x Coconut\") instead of one highlight per item."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("ACTIVER LE GROUPEMENT", "Regroupe plusieurs objets proches du même type en une seule surbrillance affichant un nombre (ex. « 3x Coconut ») au lieu d'une surbrillance par objet."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("ATTIVA RAGGRUPPAMENTO", "Raggruppa più oggetti vicini dello stesso tipo in un'unica evidenziazione con un conteggio (es. \"3x Coconut\") invece di un'evidenziazione per oggetto."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("GRUPPIERUNG AKTIVIEREN", "Fasst mehrere nahe Gegenstände derselben Art zu einer einzigen Hervorhebung mit Anzahl zusammen (z. B. „3x Coconut“) statt einer Hervorhebung pro Gegenstand."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("ACTIVAR AGRUPACIÓN", "Agrupa varios objetos cercanos del mismo tipo en un único resalte que muestra una cantidad (p. ej. «3x Coconut») en lugar de un resalte por objeto."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("ACTIVAR AGRUPACIÓN", "Agrupa varios objetos cercanos del mismo tipo en un único resalte que muestra una cantidad (por ejemplo, «3x Coconut») en lugar de un resalte por objeto."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("ATIVAR AGRUPAMENTO", "Agrupa vários itens próximos do mesmo tipo em um único destaque mostrando uma contagem (ex.: \"3x Coconut\") em vez de um destaque por item."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("ВКЛЮЧИТЬ ГРУППИРОВКУ", "Объединяет несколько соседних предметов одного вида в одну подсветку с указанием количества (например, «3x Coconut») вместо отдельной подсветки для каждого."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("УВІМКНУТИ ГРУПУВАННЯ", "Об'єднує кілька сусідніх предметів одного виду в одну підсвітку з кількістю (наприклад, «3x Coconut») замість окремої підсвітки для кожного."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("启用分组", "将附近多个同类物品合并为一个显示数量的高亮（例如“3x Coconut”），而不是每个物品单独高亮。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("啟用分組", "將附近多個同類物品合併為一個顯示數量的高亮（例如「3x Coconut」），而不是每個物品單獨高亮。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("グループ化を有効化", "近くにある同種のアイテムを個別にハイライトせず、「3x Coconut」のように個数付きの1つのハイライトにまとめます。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("그룹화 활성화", "근처의 같은 종류 아이템 여러 개를 개별 강조 표시하는 대신 개수를 표시하는 하나의 강조 표시로 묶습니다 (예: \"3x Coconut\")."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("WŁĄCZ GRUPOWANIE", "Grupuje kilka pobliskich przedmiotów tego samego rodzaju w jedno podświetlenie z licznikiem (np. „3x Coconut”) zamiast osobnego podświetlenia dla każdego."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("GRUPLAMAYI ETKİNLEŞTİR", "Yakındaki aynı türden birden fazla eşyayı, her biri için ayrı vurgu yerine sayı gösteren tek bir vurguda birleştirir (ör. \"3x Coconut\")."),
            });

            Add("enable-creature-pings", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("ENABLE CREATURE PINGS", "Also highlight creatures (beetles, spiders, capybaras, and most other mobs) when pinged, same as items/luggage. Off leaves creature pings behaving like vanilla (item/luggage highlighting is unaffected)."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("ACTIVER LES PINGS DE CRÉATURES", "Met aussi en surbrillance les créatures (scarabées, araignées, capybaras et la plupart des autres monstres) lorsqu'elles sont pingées, comme les objets/bagages. Désactivé, les pings de créatures se comportent comme dans le jeu de base (la surbrillance des objets/bagages n'est pas affectée)."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("ATTIVA PING CREATURE", "Evidenzia anche le creature (scarafaggi, ragni, capibara e la maggior parte degli altri mob) quando vengono segnalate con un ping, come oggetti/bagagli. Se disattivato, i ping alle creature si comportano come nel gioco base (l'evidenziazione di oggetti/bagagli non è interessata)."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("KREATUR-PINGS AKTIVIEREN", "Hebt beim Anpingen auch Kreaturen hervor (Käfer, Spinnen, Capybaras und die meisten anderen Mobs), genau wie Gegenstände/Gepäck. Aus lässt Kreatur-Pings sich wie im Vanilla-Spiel verhalten (Gegenstands-/Gepäck-Hervorhebung ist davon nicht betroffen)."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("ACTIVAR PINGS DE CRIATURAS", "También resalta a las criaturas (escarabajos, arañas, capibaras y la mayoría de los demás mobs) al hacerles ping, igual que objetos/equipaje. Desactivado, los pings de criaturas se comportan como en el juego original (el resalte de objetos/equipaje no se ve afectado)."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("ACTIVAR PINGS DE CRIATURAS", "También resalta a las criaturas (escarabajos, arañas, capibaras y la mayoría de los demás mobs) al hacerles ping, igual que objetos/equipaje. Desactivado, los pings de criaturas se comportan como en el juego original (el resalte de objetos/equipaje no se ve afectado)."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("ATIVAR PINGS DE CRIATURAS", "Também destaca criaturas (besouros, aranhas, capivaras e a maioria dos outros mobs) ao pingá-las, assim como itens/bagagens. Desativado, os pings de criaturas se comportam como no jogo original (o destaque de itens/bagagens não é afetado)."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("ВКЛЮЧИТЬ ПИНГИ СУЩЕСТВ", "Также подсвечивает существ (жуков, пауков, капибар и большинство других мобов) при пинге, как и предметы/багаж. При выключении пинги существ работают как в оригинальной игре (подсветка предметов/багажа не затрагивается)."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("УВІМКНУТИ ПІНГИ ІСТОТ", "Також підсвічує істот (жуків, павуків, капібар і більшість інших мобів) під час пінгу, як і предмети/багаж. При вимкненні пінги істот працюють як в оригінальній грі (підсвітка предметів/багажу не змінюється)."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("启用生物呼喊", "呼喊时也会高亮生物（甲虫、蜘蛛、水豚等大多数怪物），与物品/行李箱相同。关闭后，生物呼喊将恢复原版行为（不影响物品/行李箱高亮）。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("啟用生物呼喊", "呼喊時也會高亮生物（甲蟲、蜘蛛、水豚等大多數怪物），與物品/行李箱相同。關閉後，生物呼喊將恢復原版行為（不影響物品/行李箱高亮）。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("クリーチャーピンを有効化", "アイテム/荷物と同様に、ピンを送るとクリーチャー（甲虫、クモ、カピバラなどほとんどのモブ）もハイライト表示します。オフにするとクリーチャーピンはバニラと同じ挙動になります（アイテム/荷物のハイライトには影響しません）。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("생물체 핑 활성화", "아이템/수하물과 마찬가지로 핑을 보내면 생물체(딱정벌레, 거미, 카피바라 등 대부분의 몹)도 강조 표시합니다. 끄면 생물체 핑은 바닐라와 동일하게 동작합니다 (아이템/수하물 강조 표시에는 영향 없음)."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("WŁĄCZ PINGI STWORZEŃ", "Po zapingowaniu podświetla też stworzenia (chrząszcze, pająki, kapibary i większość innych mobów), tak jak przedmioty/bagaże. Wyłączenie sprawia, że pingi stworzeń zachowują się jak w wersji podstawowej (nie wpływa to na podświetlanie przedmiotów/bagaży)."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("YARATIK PİNGLERİNİ ETKİNLEŞTİR", "Eşyalar/bagajlar gibi, pinglendiğinde yaratıkları da (böcekler, örümcekler, kapibaralar ve diğer çoğu canlı) vurgular. Kapalıyken yaratık pingleri orijinal oyundaki gibi davranır (eşya/bagaj vurgusu etkilenmez)."),
            });

            Add("use-native-icons", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("USE NATIVE ICONS", "Show the item's own in-game icon (the art its inventory slot uses, e.g. an actual bandage for a pinged bandage) as the highlight's crosshair and its compass marker, instead of the mod's generic item-ping icon. Only items (and the campfire) have an icon in the game at all; luggage, creatures and hazards keep the generic icon either way."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("UTILISER LES ICÔNES NATIVES", "Affiche l'icône propre à l'objet dans le jeu (celle de son emplacement d'inventaire, ex. un vrai bandage pour un bandage pingé) comme réticule de la surbrillance et comme marqueur de boussole, au lieu de l'icône générique de ping du mod. Seuls les objets (et le feu de camp) ont une icône dans le jeu ; les bagages, créatures et dangers gardent l'icône générique dans tous les cas."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("USA ICONE NATIVE", "Mostra l'icona di gioco propria dell'oggetto (quella usata nel suo slot d'inventario, es. una vera benda per una benda segnalata) come mirino dell'evidenziazione e come marcatore sulla bussola, invece dell'icona generica del mod. Solo gli oggetti (e il falò) hanno un'icona nel gioco; bagagli, creature e pericoli mantengono comunque l'icona generica."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("NATIVE SYMBOLE VERWENDEN", "Zeigt das eigene Spielsymbol des Gegenstands (die Grafik seines Inventarplatzes, z. B. ein echter Verband für einen angepingten Verband) als Fadenkreuz der Hervorhebung und als Kompassmarkierung, statt des generischen Ping-Symbols des Mods. Nur Gegenstände (und das Lagerfeuer) haben überhaupt ein Symbol im Spiel; Gepäck, Kreaturen und Gefahren behalten in jedem Fall das generische Symbol."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("USAR ICONOS NATIVOS", "Muestra el icono propio del objeto en el juego (el arte que usa su ranura de inventario, p. ej. un vendaje real para un vendaje pingado) como retícula del resalte y como marcador en la brújula, en lugar del icono genérico de ping del mod. Solo los objetos (y la hoguera) tienen icono en el juego; el equipaje, las criaturas y los peligros conservan el icono genérico de todos modos."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("USAR ÍCONOS NATIVOS", "Muestra el ícono propio del objeto en el juego (el arte que usa su ranura de inventario, por ejemplo un vendaje real para un vendaje pingado) como retícula del resalte y como marcador en la brújula, en lugar del ícono genérico de ping del mod. Solo los objetos (y la fogata) tienen ícono en el juego; el equipaje, las criaturas y los peligros conservan el ícono genérico de todas formas."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("USAR ÍCONES NATIVOS", "Mostra o ícone próprio do item no jogo (a arte usada em seu slot de inventário, ex.: uma bandagem real para uma bandagem pingada) como mira do destaque e marcador na bússola, em vez do ícone genérico de ping do mod. Só itens (e a fogueira) têm ícone no jogo; bagagens, criaturas e perigos mantêm o ícone genérico de qualquer forma."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("ИСПОЛЬЗОВАТЬ РОДНЫЕ ЗНАЧКИ", "Показывает собственный игровой значок предмета (тот же, что и в ячейке инвентаря, например настоящий бинт для запингованного бинта) как перекрестие подсветки и метку на компасе, вместо стандартного значка пинга мода. Значок в игре есть только у предметов (и костра); у багажа, существ и опасностей значок всегда остаётся стандартным."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("ВИКОРИСТОВУВАТИ РІДНІ ЗНАЧКИ", "Показує власну ігрову іконку предмета (ту саму, що й у комірці інвентаря, наприклад справжній бинт для запінгованого бинта) як перехрестя підсвітки та мітку на компасі, замість стандартної іконки пінгу мода. Іконку в грі мають лише предмети (і вогнище); у багажу, істот і небезпек іконка завжди залишається стандартною."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("使用原生图标", "使用物品在游戏中自身的图标（即其物品栏格子所用的图案，例如被呼喊的绷带会显示真正的绷带图标）作为高亮的准星和指南针标记，而不是模组的通用呼喊图标。游戏中只有物品（以及篝火）才有图标；行李箱、生物和危险物始终保留通用图标。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("使用原生圖示", "使用物品在遊戲中自身的圖示（即其物品欄格子所用的圖案，例如被呼喊的繃帶會顯示真正的繃帶圖示）作為高亮的準心和指南針標記，而不是模組的通用呼喊圖示。遊戲中只有物品（以及營火）才有圖示；行李箱、生物和危險物始終保留通用圖示。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("ネイティブアイコンを使用", "MOD 独自の汎用ピンアイコンの代わりに、アイテム自身のゲーム内アイコン（インベントリ枠で使われるアートで、例えば包帯にピンを送ると実際の包帯アイコンになります）をハイライトの照準とコンパスマーカーに使用します。ゲーム内にアイコンがあるのはアイテム（と焚き火）だけで、荷物・クリーチャー・ハザードは常に汎用アイコンのままです。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("네이티브 아이콘 사용", "모드의 일반 아이템 핑 아이콘 대신, 아이템 자체의 게임 내 아이콘(인벤토리 슬롯에 사용되는 그림, 예: 붕대에 핑을 보내면 실제 붕대 아이콘)을 강조 표시의 조준선과 나침반 마커로 사용합니다. 게임에서 아이콘이 있는 것은 아이템(과 모닥불)뿐이며, 수하물/생물체/위험 요소는 항상 일반 아이콘을 유지합니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("UŻYWAJ NATYWNYCH IKON", "Pokazuje własną ikonę przedmiotu z gry (grafikę używaną w jego slocie ekwipunku, np. prawdziwy bandaż dla zapingowanego bandaża) jako celownik podświetlenia i znacznik na kompasie, zamiast ogólnej ikony pingu moda. Ikonę w grze mają tylko przedmioty (i ognisko); bagaże, stworzenia i zagrożenia zawsze zachowują ogólną ikonę."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("YERLİ SİMGELERİ KULLAN", "Modun genel eşya pingi simgesi yerine, eşyanın oyun içindeki kendi simgesini (envanter yuvasında kullanılan görsel, ör. pinglenen bir bandaj için gerçek bandaj simgesi) vurgunun nişangahı ve pusula işareti olarak gösterir. Oyunda yalnızca eşyaların (ve kamp ateşinin) simgesi vardır; bagaj, yaratık ve tehlikeler her zaman genel simgeyi korur."),
            });

            Add("name-mode", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("NAME MODE", "{enumval:ItemPingNameMode.Always} (default): every highlight shows what it is. {enumval:ItemPingNameMode.HideWhenIconShown}: anything already showing its own in-game icon (see {key:Item-Pings/use-native-icons}) drops its name, since the icon says what it is (luggage, creatures and hazards have no icon, so they keep theirs). {enumval:ItemPingNameMode.Never}: no names at all. A grouped ping keeps its count regardless (a hidden name still shows \"3x\")."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("MODE DE NOM", "{enumval:ItemPingNameMode.Always} (par défaut) : chaque surbrillance indique ce qu'elle est. {enumval:ItemPingNameMode.HideWhenIconShown} : tout ce qui affiche déjà sa propre icône de jeu (voir {key:Item-Pings/use-native-icons}) perd son nom, puisque l'icône le dit déjà (les bagages, créatures et dangers n'ont pas d'icône, donc ils gardent le leur). {enumval:ItemPingNameMode.Never} : aucun nom du tout. Un ping groupé garde son compte dans tous les cas (un nom masqué affiche quand même « 3x »)."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("MODALITÀ NOME", "{enumval:ItemPingNameMode.Always} (predefinito): ogni evidenziazione mostra cos'è. {enumval:ItemPingNameMode.HideWhenIconShown}: tutto ciò che mostra già la propria icona di gioco (vedi {key:Item-Pings/use-native-icons}) perde il nome, poiché l'icona lo indica già (bagagli, creature e pericoli non hanno icona, quindi mantengono il proprio nome). {enumval:ItemPingNameMode.Never}: nessun nome. Un ping raggruppato mantiene comunque il conteggio (un nome nascosto mostra comunque \"3x\")."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("NAMENSMODUS", "{enumval:ItemPingNameMode.Always} (Standard): jede Hervorhebung zeigt, was sie ist. {enumval:ItemPingNameMode.HideWhenIconShown}: alles, das bereits sein eigenes Spielsymbol zeigt (siehe {key:Item-Pings/use-native-icons}), verliert seinen Namen, da das Symbol es schon sagt (Gepäck, Kreaturen und Gefahren haben kein Symbol, behalten also ihren Namen). {enumval:ItemPingNameMode.Never}: gar keine Namen. Ein gruppierter Ping behält seine Anzahl trotzdem (ein verborgener Name zeigt weiterhin „3x“)."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("MODO DE NOMBRE", "{enumval:ItemPingNameMode.Always} (predeterminado): cada resalte muestra qué es. {enumval:ItemPingNameMode.HideWhenIconShown}: cualquier cosa que ya muestre su propio icono de juego (ver {key:Item-Pings/use-native-icons}) pierde su nombre, ya que el icono ya lo indica (el equipaje, las criaturas y los peligros no tienen icono, así que conservan el suyo). {enumval:ItemPingNameMode.Never}: sin nombres en absoluto. Un ping agrupado conserva su recuento de todos modos (un nombre oculto sigue mostrando «3x»)."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("MODO DE NOMBRE", "{enumval:ItemPingNameMode.Always} (predeterminado): cada resalte muestra qué es. {enumval:ItemPingNameMode.HideWhenIconShown}: cualquier cosa que ya muestre su propio ícono de juego (ver {key:Item-Pings/use-native-icons}) pierde su nombre, ya que el ícono ya lo indica (el equipaje, las criaturas y los peligros no tienen ícono, así que conservan el suyo). {enumval:ItemPingNameMode.Never}: sin nombres en absoluto. Un ping agrupado conserva su conteo de todos modos (un nombre oculto sigue mostrando «3x»)."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("MODO DE NOME", "{enumval:ItemPingNameMode.Always} (padrão): cada destaque mostra o que é. {enumval:ItemPingNameMode.HideWhenIconShown}: qualquer coisa que já mostre seu próprio ícone do jogo (ver {key:Item-Pings/use-native-icons}) perde o nome, já que o ícone já diz o que é (bagagens, criaturas e perigos não têm ícone, então mantêm o nome). {enumval:ItemPingNameMode.Never}: nenhum nome. Um ping agrupado mantém sua contagem de qualquer forma (um nome oculto ainda mostra \"3x\")."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("РЕЖИМ НАЗВАНИЯ", "{enumval:ItemPingNameMode.Always} (по умолчанию): каждая подсветка показывает, что это. {enumval:ItemPingNameMode.HideWhenIconShown}: у всего, что уже показывает свой игровой значок (см. {key:Item-Pings/use-native-icons}), название скрывается, так как значок уже всё говорит (у багажа, существ и опасностей нет значка, поэтому название у них остаётся). {enumval:ItemPingNameMode.Never}: названия не показываются вовсе. Сгруппированный пинг всё равно сохраняет счётчик (скрытое название всё равно покажет «3x»)."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("РЕЖИМ НАЗВИ", "{enumval:ItemPingNameMode.Always} (за замовчуванням): кожна підсвітка показує, що це. {enumval:ItemPingNameMode.HideWhenIconShown}: у всього, що вже показує свою ігрову іконку (див. {key:Item-Pings/use-native-icons}), назва приховується, оскільки іконка вже все каже (у багажу, істот і небезпек немає іконки, тому назва в них залишається). {enumval:ItemPingNameMode.Never}: назви не показуються взагалі. Згрупований пінг усе одно зберігає лічильник (прихована назва все одно покаже «3x»)."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("名称显示模式", "{enumval:ItemPingNameMode.Always}（默认）：每个高亮都显示其名称。{enumval:ItemPingNameMode.HideWhenIconShown}：任何已经显示自身游戏内图标的物品（见 {key:Item-Pings/use-native-icons}）都会隐藏名称，因为图标已经说明了它是什么（行李箱、生物和危险物没有图标，因此会保留名称）。{enumval:ItemPingNameMode.Never}：完全不显示名称。分组呼喊无论如何都会保留数量（隐藏名称时仍会显示“3x”）。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("名稱顯示模式", "{enumval:ItemPingNameMode.Always}（預設）：每個高亮都顯示其名稱。{enumval:ItemPingNameMode.HideWhenIconShown}：任何已經顯示自身遊戲內圖示的物品（見 {key:Item-Pings/use-native-icons}）都會隱藏名稱，因為圖示已經說明了它是什麼（行李箱、生物和危險物沒有圖示，因此會保留名稱）。{enumval:ItemPingNameMode.Never}：完全不顯示名稱。分組呼喊無論如何都會保留數量（隱藏名稱時仍會顯示「3x」）。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("名前表示モード", "{enumval:ItemPingNameMode.Always}（デフォルト）：すべてのハイライトに名前を表示します。{enumval:ItemPingNameMode.HideWhenIconShown}：すでに自身のゲーム内アイコンを表示しているもの（{key:Item-Pings/use-native-icons} 参照）は、アイコンが何かを示しているため名前を非表示にします（荷物、クリーチャー、ハザードにはアイコンがないため名前を維持します）。{enumval:ItemPingNameMode.Never}：名前を一切表示しません。グループ化されたピンは名前が非表示でも個数（「3x」など）は表示され続けます。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("이름 표시 모드", "{enumval:ItemPingNameMode.Always}(기본값): 모든 강조 표시에 이름이 나타납니다. {enumval:ItemPingNameMode.HideWhenIconShown}: 이미 자체 게임 내 아이콘을 표시 중인 대상({key:Item-Pings/use-native-icons} 참고)은 아이콘이 무엇인지 알려주므로 이름을 숨깁니다 (수하물, 생물체, 위험 요소는 아이콘이 없어 이름을 유지합니다). {enumval:ItemPingNameMode.Never}: 이름을 전혀 표시하지 않습니다. 그룹화된 핑은 이름이 숨겨져도 개수(\"3x\" 등)는 계속 표시됩니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("TRYB NAZWY", "{enumval:ItemPingNameMode.Always} (domyślnie): każde podświetlenie pokazuje, czym jest. {enumval:ItemPingNameMode.HideWhenIconShown}: wszystko, co już pokazuje własną ikonę z gry (zob. {key:Item-Pings/use-native-icons}), traci nazwę, bo ikona już to mówi (bagaże, stworzenia i zagrożenia nie mają ikony, więc zachowują nazwę). {enumval:ItemPingNameMode.Never}: brak nazw w ogóle. Zgrupowany ping i tak zachowuje licznik (ukryta nazwa nadal pokazuje „3x”)."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("İSİM MODU", "{enumval:ItemPingNameMode.Always} (varsayılan): her vurgu ne olduğunu gösterir. {enumval:ItemPingNameMode.HideWhenIconShown}: kendi oyun içi simgesini zaten gösteren her şey (bkz. {key:Item-Pings/use-native-icons}) adını gizler, çünkü simge zaten ne olduğunu söyler (bagaj, yaratık ve tehlikelerin simgesi olmadığından adlarını korurlar). {enumval:ItemPingNameMode.Never}: hiç isim gösterilmez. Gruplanmış bir ping yine de sayısını korur (gizli isimde bile \"3x\" görünür)."),
            });

            Add("show-distance", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("SHOW DISTANCE", "Show a distance sub-line under the item/luggage highlight."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("AFFICHER LA DISTANCE", "Affiche une ligne de distance sous la surbrillance de l'objet/du bagage."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("MOSTRA DISTANZA", "Mostra una riga di distanza sotto l'evidenziazione dell'oggetto/bagaglio."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("ENTFERNUNG ANZEIGEN", "Zeigt eine Entfernungszeile unter der Gegenstands-/Gepäck-Hervorhebung an."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("MOSTRAR DISTANCIA", "Muestra una línea de distancia bajo el resalte del objeto/equipaje."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("MOSTRAR DISTANCIA", "Muestra una línea de distancia bajo el resalte del objeto/equipaje."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("MOSTRAR DISTÂNCIA", "Mostra uma linha de distância abaixo do destaque do item/bagagem."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("ПОКАЗЫВАТЬ РАССТОЯНИЕ", "Показывает строку расстояния под подсветкой предмета/багажа."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("ПОКАЗУВАТИ ВІДСТАНЬ", "Показує рядок відстані під підсвіткою предмета/багажу."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("显示距离", "在物品/行李箱高亮下方显示距离子行。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("顯示距離", "在物品/行李箱高亮下方顯示距離子行。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("距離を表示", "アイテム/荷物のハイライトの下に距離のサブラインを表示します。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("거리 표시", "아이템/수하물 강조 표시 아래에 거리 보조 줄을 표시합니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("POKAŻ ODLEGŁOŚĆ", "Pokazuje linię odległości pod podświetleniem przedmiotu/bagażu."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("MESAFEYİ GÖSTER", "Eşya/bagaj vurgusunun altında bir mesafe alt satırı gösterir."),
            });

            Add("enable-offscreen-indicator", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("ENABLE OFFSCREEN INDICATOR", "Show an edge-of-screen arrow pointing toward a highlighted item/luggage when it's off-screen, same mechanism as the ping indicator. Moot while {key:General/item-ping-placement} is {enumval:IndicatorPlacement.CompassOnly}, which hides the whole edge-of-screen widget anyway."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("ACTIVER L'INDICATEUR HORS ÉCRAN", "Affiche une flèche au bord de l'écran pointant vers un objet/bagage en surbrillance lorsqu'il est hors écran, même mécanisme que l'indicateur de ping. Sans effet si {key:General/item-ping-placement} est réglé sur {enumval:IndicatorPlacement.CompassOnly}, qui masque de toute façon tout le widget de bord d'écran."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("ATTIVA INDICATORE FUORI SCHERMO", "Mostra una freccia sul bordo dello schermo che punta verso un oggetto/bagaglio evidenziato quando è fuori schermo, stesso meccanismo dell'indicatore di ping. Ininfluente se {key:General/item-ping-placement} è impostato su {enumval:IndicatorPlacement.CompassOnly}, che nasconde comunque l'intero widget di bordo schermo."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("BILDSCHIRMRAND-ANZEIGE AKTIVIEREN", "Zeigt einen Pfeil am Bildschirmrand, der auf einen hervorgehobenen Gegenstand/Gepäckstück zeigt, wenn dieser außerhalb des Bildschirms ist - derselbe Mechanismus wie beim Ping-Indikator. Wirkungslos, solange {key:General/item-ping-placement} auf {enumval:IndicatorPlacement.CompassOnly} steht, was das gesamte Bildschirmrand-Widget ohnehin ausblendet."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("ACTIVAR INDICADOR FUERA DE PANTALLA", "Muestra una flecha en el borde de la pantalla que apunta hacia un objeto/equipaje resaltado cuando está fuera de pantalla, el mismo mecanismo que el indicador de ping. Sin efecto mientras {key:General/item-ping-placement} esté en {enumval:IndicatorPlacement.CompassOnly}, que oculta todo el widget de borde de pantalla de todos modos."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("ACTIVAR INDICADOR FUERA DE PANTALLA", "Muestra una flecha en el borde de la pantalla que apunta hacia un objeto/equipaje resaltado cuando está fuera de pantalla, el mismo mecanismo que el indicador de ping. Sin efecto mientras {key:General/item-ping-placement} esté en {enumval:IndicatorPlacement.CompassOnly}, que de todos modos oculta todo el widget de borde de pantalla."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("ATIVAR INDICADOR FORA DA TELA", "Mostra uma seta na borda da tela apontando para um item/bagagem destacado quando está fora da tela, mesmo mecanismo do indicador de ping. Sem efeito enquanto {key:General/item-ping-placement} estiver como {enumval:IndicatorPlacement.CompassOnly}, que oculta todo o widget de borda da tela de qualquer forma."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("ВКЛЮЧИТЬ ИНДИКАТОР ЗА ЭКРАНОМ", "Показывает стрелку у края экрана, указывающую на подсвеченный предмет/багаж, когда он вне экрана - тот же механизм, что и у индикатора пинга. Не действует, если {key:General/item-ping-placement} установлено в {enumval:IndicatorPlacement.CompassOnly}, поскольку тогда весь виджет края экрана всё равно скрыт."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("УВІМКНУТИ ІНДИКАТОР ПОЗА ЕКРАНОМ", "Показує стрілку біля краю екрана, що вказує на підсвічений предмет/багаж, коли він поза екраном - той самий механізм, що й у індикатора пінгу. Не діє, якщо {key:General/item-ping-placement} встановлено в {enumval:IndicatorPlacement.CompassOnly}, оскільки тоді весь віджет краю екрана все одно прихований."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("启用离屏指示器", "当高亮的物品/行李箱离开屏幕时，在屏幕边缘显示指向它的箭头，机制与呼喊指示器相同。当 {key:General/item-ping-placement} 设为 {enumval:IndicatorPlacement.CompassOnly} 时无效，因为此时整个屏幕边缘控件都会被隐藏。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("啟用離螢幕指示器", "當高亮的物品/行李箱離開螢幕時，在螢幕邊緣顯示指向它的箭頭，機制與呼喊指示器相同。當 {key:General/item-ping-placement} 設為 {enumval:IndicatorPlacement.CompassOnly} 時無效，因為此時整個螢幕邊緣控件都會被隱藏。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("画面外インジケーターを有効化", "ハイライトされたアイテム/荷物が画面外にあるとき、ピンインジケーターと同じ仕組みで画面端に矢印を表示します。{key:General/item-ping-placement} が {enumval:IndicatorPlacement.CompassOnly} の場合、画面端ウィジェット自体が非表示になるため無意味です。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("화면 밖 표시기 활성화", "강조된 아이템/수하물이 화면 밖에 있을 때 핑 표시기와 동일한 방식으로 화면 가장자리에 화살표를 표시합니다. {key:General/item-ping-placement}가 {enumval:IndicatorPlacement.CompassOnly}로 설정되어 있으면 화면 가장자리 위젯 전체가 어차피 숨겨지므로 의미가 없습니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("WŁĄCZ WSKAŹNIK POZA EKRANEM", "Pokazuje strzałkę przy krawędzi ekranu wskazującą na podświetlony przedmiot/bagaż, gdy jest poza ekranem - ten sam mechanizm co wskaźnik pingu. Bez znaczenia, gdy {key:General/item-ping-placement} jest ustawione na {enumval:IndicatorPlacement.CompassOnly}, ponieważ wtedy cały widżet krawędzi ekranu jest i tak ukryty."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("EKRAN DIŞI GÖSTERGEYİ ETKİNLEŞTİR", "Vurgulanan bir eşya/bagaj ekran dışına çıktığında, ping göstergesiyle aynı mekanizmayla ekran kenarında ona doğru bir ok gösterir. {key:General/item-ping-placement} {enumval:IndicatorPlacement.CompassOnly} iken anlamsızdır, çünkü bu durumda ekran kenarı bileşeninin tamamı zaten gizlenir."),
            });
        }
    }
}
