using System.Collections.Generic;

namespace SenseOfDirection.Ui.Localization.Config
{
    /// <summary>Localized names/descriptions for every "Item-Ping-Detection" section config entry.</summary>
    internal static class ItemPingDetectionConfigLocalization
    {
        internal static void Register(ConfigLocalizationTable.Registry registry)
        {
            void Add(string key, Dictionary<LocalizedText.Language, ConfigLocalizationEntry> table) =>
                registry.Add("Item-Ping-Detection", key, table);

            Add("item-radius-meters", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("ITEM RADIUS METERS", "How close a ping needs to land to an item for it to get highlighted."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("RAYON OBJET EN MÈTRES", "À quelle distance un ping doit atterrir d'un objet pour qu'il soit mis en surbrillance."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("RAGGIO OGGETTO IN METRI", "Quanto vicino deve cadere un ping a un oggetto perché venga evidenziato."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("GEGENSTANDSRADIUS IN METERN", "Wie nah ein Ping an einem Gegenstand landen muss, damit dieser hervorgehoben wird."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("RADIO DE OBJETO EN METROS", "A qué distancia debe caer un ping de un objeto para que se resalte."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("RADIO DE OBJETO EN METROS", "A qué distancia debe caer un ping de un objeto para que se resalte."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("RAIO DE ITEM EM METROS", "A que distância um ping precisa cair de um item para que ele seja destacado."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("РАДИУС ПРЕДМЕТА В МЕТРАХ", "Насколько близко пинг должен упасть к предмету, чтобы тот был подсвечен."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("РАДІУС ПРЕДМЕТА В МЕТРАХ", "Наскільки близько пінг має впасти до предмета, щоб той підсвітився."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("物品判定半径（米）", "呼喊需要落在离物品多近的范围内才能使其高亮。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("物品判定半徑（公尺）", "呼喊需要落在離物品多近的範圍內才能使其高亮。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("アイテム判定半径（メートル）", "アイテムがハイライトされるために、ピンがどれだけ近くに着弾する必要があるかです。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("아이템 반경(미터)", "아이템이 강조 표시되려면 핑이 얼마나 가까이 떨어져야 하는지입니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("PROMIEŃ PRZEDMIOTU W METRACH", "Jak blisko przedmiotu musi wylądować ping, aby ten został podświetlony."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("EŞYA YARIÇAPI (METRE)", "Bir eşyanın vurgulanması için pingin ona ne kadar yakın düşmesi gerektiği."),
            });

            Add("luggage-radius-meters", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("LUGGAGE RADIUS METERS", "Same as {key:Item-Ping-Detection/item-radius-meters}, but for luggage. Larger by default, since luggage is a bigger target."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("RAYON BAGAGE EN MÈTRES", "Comme {key:Item-Ping-Detection/item-radius-meters}, mais pour les bagages. Plus grand par défaut, car un bagage est une cible plus grande."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("RAGGIO BAGAGLIO IN METRI", "Come {key:Item-Ping-Detection/item-radius-meters}, ma per i bagagli. Più grande di default, poiché il bagaglio è un bersaglio più grande."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("GEPÄCKRADIUS IN METERN", "Wie {key:Item-Ping-Detection/item-radius-meters}, aber für Gepäck. Standardmäßig größer, da Gepäck ein größeres Ziel ist."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("RADIO DE EQUIPAJE EN METROS", "Igual que {key:Item-Ping-Detection/item-radius-meters}, pero para el equipaje. Mayor por defecto, ya que el equipaje es un objetivo más grande."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("RADIO DE EQUIPAJE EN METROS", "Igual que {key:Item-Ping-Detection/item-radius-meters}, pero para el equipaje. Mayor por defecto, ya que el equipaje es un objetivo más grande."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("RAIO DE BAGAGEM EM METROS", "O mesmo que {key:Item-Ping-Detection/item-radius-meters}, mas para bagagens. Maior por padrão, já que a bagagem é um alvo maior."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("РАДИУС БАГАЖА В МЕТРАХ", "То же самое, что {key:Item-Ping-Detection/item-radius-meters}, но для багажа. По умолчанию больше, так как багаж — более крупная цель."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("РАДІУС БАГАЖУ В МЕТРАХ", "Те саме, що й {key:Item-Ping-Detection/item-radius-meters}, але для багажу. За замовчуванням більший, оскільки багаж - більша ціль."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("行李箱判定半径（米）", "与 {key:Item-Ping-Detection/item-radius-meters} 相同，但用于行李箱。由于行李箱目标更大，默认值也更大。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("行李箱判定半徑（公尺）", "與 {key:Item-Ping-Detection/item-radius-meters} 相同，但用於行李箱。由於行李箱目標更大，預設值也更大。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("荷物判定半径（メートル）", "{key:Item-Ping-Detection/item-radius-meters} と同じですが、荷物用です。荷物は的が大きいため、デフォルト値も大きめです。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("수하물 반경(미터)", "{key:Item-Ping-Detection/item-radius-meters}와 동일하지만 수하물용입니다. 수하물은 더 큰 목표물이므로 기본값도 더 큽니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("PROMIEŃ BAGAŻU W METRACH", "To samo co {key:Item-Ping-Detection/item-radius-meters}, ale dla bagażu. Domyślnie większy, ponieważ bagaż jest większym celem."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("BAGAJ YARIÇAPI (METRE)", "{key:Item-Ping-Detection/item-radius-meters} ile aynı, ancak bagaj için. Bagaj daha büyük bir hedef olduğundan varsayılan olarak daha büyüktür."),
            });

            Add("enable-hit-assist", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("ENABLE HIT ASSIST", "Widen the ping's own aim raycast so it can land directly on an item/luggage's own collider (not just terrain/ground), instead of phasing through to whatever's behind it. Fixes hard-to-ping items like a coconut up a tree or a small dropped item. Off falls back to vanilla's own terrain-only ping raycast."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("ACTIVER L'ASSISTANCE DE VISÉE", "Élargit le rayon de visée du ping pour qu'il puisse atterrir directement sur le collider propre d'un objet/bagage (pas seulement le terrain/sol), au lieu de le traverser vers ce qui se trouve derrière. Corrige les objets difficiles à pinger comme une noix de coco en haut d'un arbre ou un petit objet au sol. Désactivé, revient au rayon de ping du jeu de base limité au terrain."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("ATTIVA ASSISTENZA MIRA", "Allarga il raycast di mira del ping in modo che possa colpire direttamente il collider di un oggetto/bagaglio (non solo terreno/suolo), invece di attraversarlo verso ciò che si trova dietro. Risolve il problema degli oggetti difficili da pingare, come una noce di cocco su un albero o un piccolo oggetto caduto. Disattivato, torna al raycast del ping limitato al solo terreno del gioco base."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("TREFFERHILFE AKTIVIEREN", "Verbreitert den eigenen Ziel-Raycast des Pings, sodass er direkt auf dem Collider eines Gegenstands/Gepäckstücks landen kann (nicht nur auf Gelände/Boden), statt hindurchzugehen zu dem, was dahinterliegt. Behebt schwer anzupingende Gegenstände wie eine Kokosnuss oben in einem Baum oder einen kleinen fallengelassenen Gegenstand. Aus fällt zurück auf den reinen Gelände-Ping-Raycast des Vanilla-Spiels."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("ACTIVAR ASISTENCIA DE IMPACTO", "Ensancha el rayo de puntería propio del ping para que pueda aterrizar directamente sobre el collider de un objeto/equipaje (no solo terreno/suelo), en lugar de atravesarlo hacia lo que hay detrás. Soluciona objetos difíciles de pingar, como un coco en lo alto de un árbol o un pequeño objeto caído. Desactivado, vuelve al rayo de ping original limitado al terreno."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("ACTIVAR ASISTENCIA DE IMPACTO", "Ensancha el rayo de puntería propio del ping para que pueda aterrizar directamente sobre el collider de un objeto/equipaje (no solo terreno/suelo), en lugar de atravesarlo hacia lo que hay detrás. Soluciona objetos difíciles de pingar, como un coco en lo alto de un árbol o un pequeño objeto caído. Desactivado, vuelve al rayo de ping original limitado al terreno."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("ATIVAR ASSISTÊNCIA DE ACERTO", "Alarga o raycast de mira do próprio ping para que ele possa cair diretamente no collider de um item/bagagem (não só no terreno/chão), em vez de atravessar para o que está atrás. Corrige itens difíceis de pingar, como um coco no alto de uma árvore ou um item pequeno no chão. Desativado, volta ao raycast de ping original limitado ao terreno."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("ВКЛЮЧИТЬ ПОМОЩЬ ПОПАДАНИЯ", "Расширяет собственный луч прицеливания пинга, чтобы он мог попадать прямо в коллайдер предмета/багажа (а не только в местность/землю), вместо того чтобы проходить сквозь них к тому, что находится позади. Исправляет проблему с трудными для пинга предметами вроде кокоса на дереве или маленького упавшего предмета. При выключении используется обычный луч пинга оригинальной игры, реагирующий только на местность."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("УВІМКНУТИ ДОПОМОГУ ПОПАДАННЯ", "Розширює власний промінь прицілювання пінгу, щоб він міг влучати прямо в колайдер предмета/багажу (а не лише в місцевість/землю), замість того, щоб проходити крізь них до того, що позаду. Виправляє проблему з важкими для пінгу предметами на кшталт кокоса на дереві або маленького впалого предмета. При вимкненні використовується звичайний промінь пінгу оригінальної гри, що реагує лише на місцевість."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("启用命中辅助", "加宽呼喊自身的瞄准射线，使其能直接命中物品/行李箱自身的碰撞体（而不仅是地形/地面），而不是穿透到其后方的东西。修复难以呼喊的物品，例如树上的椰子或掉落的小物品。关闭后将退回原版仅对地形生效的呼喊射线。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("啟用命中輔助", "加寬呼喊自身的瞄準射線，使其能直接命中物品/行李箱自身的碰撞體（而不僅是地形/地面），而不是穿透到其後方的東西。修復難以呼喊的物品，例如樹上的椰子或掉落的小物品。關閉後將退回原版僅對地形生效的呼喊射線。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("命中アシストを有効化", "ピン自体の照準レイキャストを広げ、背後にあるものへ突き抜けるのではなく、アイテム/荷物自身のコライダー（地形/地面だけでなく）に直接命中できるようにします。木の上のココナッツや小さな落とし物などピンを送りにくいアイテムの問題を解消します。オフにすると、地形にのみ反応するバニラのピンレイキャストに戻ります。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("명중 보조 활성화", "핑 자체의 조준 레이캐스트를 넓혀 지형/땅뿐 아니라 아이템/수하물 자체의 콜라이더에 직접 명중할 수 있게 합니다(뒤에 있는 것을 그대로 통과하지 않음). 나무 위의 코코넛이나 떨어진 작은 아이템처럼 핑을 보내기 어려운 아이템 문제를 해결합니다. 끄면 지형에만 반응하는 바닐라 핑 레이캐스트로 돌아갑니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("WŁĄCZ WSPOMAGANIE TRAFIEŃ", "Poszerza własny promień celowania pingu, aby mógł trafiać bezpośrednio w kolizję przedmiotu/bagażu (nie tylko teren/ziemię), zamiast przenikać do tego, co jest za nim. Naprawia trudne do zapingowania przedmioty, jak kokos na drzewie czy mały upuszczony przedmiot. Wyłączenie przywraca zwykły promień pingu z wersji podstawowej, reagujący tylko na teren."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("İSABET YARDIMINI ETKİNLEŞTİR", "Pingin kendi nişan ışınını genişletir, böylece arkasındaki şeye geçmek yerine doğrudan bir eşyanın/bagajın kendi çarpışma alanına inebilir (sadece arazi/zemine değil). Bir ağaçtaki hindistan cevizi veya küçük düşmüş bir eşya gibi pinglenmesi zor eşyaları düzeltir. Kapalıyken yalnızca araziye tepki veren orijinal ping ışınına döner."),
            });

            Add("hitbox-radius-meters", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("HITBOX RADIUS METERS", "Only used when {key:Item-Ping-Detection/enable-hit-assist} is on. Treats the ping raycast as a sphere of this radius instead of an infinitely-thin line, so aiming near (not pixel-perfect on) an item's collider still hits it. 0 disables the sphere, falling back to a plain (still item-widened) raycast."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("RAYON DE ZONE DE COLLISION EN MÈTRES", "Utilisé uniquement si {key:Item-Ping-Detection/enable-hit-assist} est activé. Traite le rayon de ping comme une sphère de ce rayon au lieu d'une ligne infiniment fine, afin que viser près (pas au pixel près) du collider d'un objet le touche quand même. 0 désactive la sphère et revient à un rayon simple (toujours élargi pour les objets)."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("RAGGIO HITBOX IN METRI", "Usato solo quando {key:Item-Ping-Detection/enable-hit-assist} è attivo. Tratta il raycast del ping come una sfera di questo raggio invece che come una linea infinitamente sottile, così mirare vicino (non con precisione al pixel) al collider di un oggetto lo colpisce comunque. 0 disattiva la sfera, tornando a un raycast semplice (comunque allargato per gli oggetti)."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("HITBOX-RADIUS IN METERN", "Nur verwendet, wenn {key:Item-Ping-Detection/enable-hit-assist} aktiv ist. Behandelt den Ping-Raycast als Kugel mit diesem Radius statt als unendlich dünne Linie, sodass ein Zielen in der Nähe (nicht pixelgenau) des Colliders eines Gegenstands ihn trotzdem trifft. 0 deaktiviert die Kugel und fällt auf einen einfachen (weiterhin gegenstandsverbreiterten) Raycast zurück."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("RADIO DE HITBOX EN METROS", "Solo se usa cuando {key:Item-Ping-Detection/enable-hit-assist} está activado. Trata el rayo de ping como una esfera de este radio en lugar de una línea infinitamente fina, de modo que apuntar cerca (no con precisión de píxel) del collider de un objeto igual lo golpea. 0 desactiva la esfera, volviendo a un rayo simple (aún ensanchado para objetos)."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("RADIO DE HITBOX EN METROS", "Solo se usa cuando {key:Item-Ping-Detection/enable-hit-assist} está activado. Trata el rayo de ping como una esfera de este radio en lugar de una línea infinitamente fina, de modo que apuntar cerca (no con precisión de píxel) del collider de un objeto igual lo golpea. 0 desactiva la esfera, volviendo a un rayo simple (aún ensanchado para objetos)."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("RAIO DA HITBOX EM METROS", "Usado apenas quando {key:Item-Ping-Detection/enable-hit-assist} está ativado. Trata o raycast do ping como uma esfera desse raio em vez de uma linha infinitamente fina, então mirar perto (não com precisão de pixel) do collider de um item ainda o acerta. 0 desativa a esfera, voltando a um raycast simples (ainda alargado para itens)."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("РАДИУС ХИТБОКСА В МЕТРАХ", "Используется только при включённом {key:Item-Ping-Detection/enable-hit-assist}. Рассматривает луч пинга как сферу этого радиуса вместо бесконечно тонкой линии, поэтому прицеливание рядом с коллайдером предмета (не идеально точно) всё равно попадает в него. 0 отключает сферу, возвращая обычный (всё ещё расширенный для предметов) луч."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("РАДІУС ХІТБОКСА В МЕТРАХ", "Використовується лише коли увімкнено {key:Item-Ping-Detection/enable-hit-assist}. Розглядає промінь пінгу як сферу цього радіуса замість нескінченно тонкої лінії, тому прицілювання поруч із колайдером предмета (не ідеально точно) все одно влучає в нього. 0 вимикає сферу, повертаючи звичайний (все ще розширений для предметів) промінь."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("命中箱半径（米）", "仅在 {key:Item-Ping-Detection/enable-hit-assist} 开启时生效。将呼喊射线视为一个此半径的球体，而非无限细的直线，因此瞄准物品碰撞体附近（无需像素级精确）也能命中。设为 0 会禁用该球体，退回为普通（仍对物品加宽的）射线。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("命中箱半徑（公尺）", "僅在 {key:Item-Ping-Detection/enable-hit-assist} 開啟時生效。將呼喊射線視為一個此半徑的球體，而非無限細的直線，因此瞄準物品碰撞體附近（無需像素級精確）也能命中。設為 0 會停用該球體，退回為普通（仍對物品加寬的）射線。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("ヒットボックス半径（メートル）", "{key:Item-Ping-Detection/enable-hit-assist} が有効な場合のみ使用されます。ピンのレイキャストを無限に細い線ではなく、この半径の球として扱うため、アイテムのコライダー付近を狙えば（ピクセル単位で正確でなくても）命中します。0 にすると球判定は無効になり、通常の（アイテム分は広げられたままの）レイキャストに戻ります。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("히트박스 반경(미터)", "{key:Item-Ping-Detection/enable-hit-assist}가 켜져 있을 때만 사용됩니다. 핑 레이캐스트를 무한히 얇은 선이 아니라 이 반경의 구체로 취급하여, 아이템 콜라이더 근처(픽셀 단위로 정확하지 않아도)를 조준해도 명중합니다. 0으로 설정하면 구체 판정이 비활성화되어 일반(아이템에 대해서는 여전히 넓혀진) 레이캐스트로 돌아갑니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("PROMIEŃ HITBOXA W METRACH", "Używane tylko gdy {key:Item-Ping-Detection/enable-hit-assist} jest włączone. Traktuje promień pingu jako kulę o tym promieniu zamiast nieskończenie cienkiej linii, więc celowanie blisko (nie idealnie precyzyjnie) kolizji przedmiotu nadal go trafia. 0 wyłącza kulę, przywracając zwykły (nadal poszerzony dla przedmiotów) promień."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("ÇARPIŞMA KUTUSU YARIÇAPI (METRE)", "Yalnızca {key:Item-Ping-Detection/enable-hit-assist} açıkken kullanılır. Ping ışınını sonsuz ince bir çizgi yerine bu yarıçapta bir küre olarak ele alır, böylece bir eşyanın çarpışma alanına yakın (piksel hassasiyetinde değil) nişan alınsa bile isabet eder. 0 küreyi devre dışı bırakır ve düz (yine de eşyalar için genişletilmiş) bir ışına döner."),
            });

            Add("enable-ray-assist", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("ENABLE RAY ASSIST", "Also count an item/luggage as pinged if it's close enough to your aim line, independent of physics entirely. Needed for items that aren't pushable/hittable until first picked up (an unpicked coconut on a tree, berries on a bush, something freshly spawned from opened luggage); their collider is disabled until then, so no physics raycast (not even {key:Item-Ping-Detection/enable-hit-assist}'s) can ever land on them."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("ACTIVER L'ASSISTANCE DE RAYON", "Compte aussi un objet/bagage comme pingé s'il est assez proche de votre ligne de visée, indépendamment de toute physique. Nécessaire pour les objets non poussables/frappables tant qu'ils n'ont pas été ramassés une première fois (une noix de coco non cueillie sur un arbre, des baies sur un buisson, quelque chose qui vient d'apparaître d'un bagage ouvert) ; leur collider est désactivé jusque-là, donc aucun rayon physique (même celui d'{key:Item-Ping-Detection/enable-hit-assist}) ne peut jamais les atteindre."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("ATTIVA ASSISTENZA RAGGIO", "Considera pingato anche un oggetto/bagaglio se è abbastanza vicino alla tua linea di mira, indipendentemente dalla fisica. Necessario per oggetti non spingibili/colpibili finché non vengono raccolti la prima volta (una noce di cocco non colta su un albero, bacche su un cespuglio, qualcosa appena apparso da un bagaglio aperto); il loro collider è disattivato fino ad allora, quindi nessun raycast fisico (nemmeno quello di {key:Item-Ping-Detection/enable-hit-assist}) può mai colpirli."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("STRAHLHILFE AKTIVIEREN", "Zählt einen Gegenstand/Gepäckstück auch dann als angepingt, wenn er nah genug an deiner Ziellinie ist, völlig unabhängig von der Physik. Nötig für Gegenstände, die erst nach dem ersten Aufheben stoß-/treffbar sind (eine ungepflückte Kokosnuss im Baum, Beeren an einem Busch, etwas frisch aus geöffnetem Gepäck Erschienenes); ihr Collider ist bis dahin deaktiviert, sodass kein physikalischer Raycast (auch nicht der von {key:Item-Ping-Detection/enable-hit-assist}) sie je treffen kann."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("ACTIVAR ASISTENCIA DE RAYO", "También cuenta un objeto/equipaje como pingado si está lo bastante cerca de tu línea de puntería, sin depender de la física en absoluto. Necesario para objetos que no se pueden empujar/golpear hasta ser recogidos por primera vez (un coco sin recoger en un árbol, bayas en un arbusto, algo recién aparecido de un equipaje abierto); su collider está desactivado hasta entonces, así que ningún rayo físico (ni siquiera el de {key:Item-Ping-Detection/enable-hit-assist}) puede alcanzarlos."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("ACTIVAR ASISTENCIA DE RAYO", "También cuenta un objeto/equipaje como pingado si está lo bastante cerca de tu línea de puntería, sin depender de la física en absoluto. Necesario para objetos que no se pueden empujar/golpear hasta ser recogidos por primera vez (un coco sin recoger en un árbol, bayas en un arbusto, algo recién aparecido de un equipaje abierto); su collider está desactivado hasta entonces, así que ningún rayo físico (ni siquiera el de {key:Item-Ping-Detection/enable-hit-assist}) puede alcanzarlos."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("ATIVAR ASSISTÊNCIA DE RAIO", "Também conta um item/bagagem como pingado se estiver perto o suficiente da sua linha de mira, independentemente da física. Necessário para itens que não são empurráveis/atingíveis até serem pegos pela primeira vez (um coco não colhido em uma árvore, frutas em um arbusto, algo recém-surgido de uma bagagem aberta); o collider deles fica desativado até então, então nenhum raycast físico (nem mesmo o do {key:Item-Ping-Detection/enable-hit-assist}) consegue acertá-los."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("ВКЛЮЧИТЬ ПОМОЩЬ ЛУЧА", "Также засчитывает предмет/багаж как запингованный, если он достаточно близко к линии прицеливания, полностью независимо от физики. Нужно для предметов, которые нельзя толкнуть/задеть, пока их не подобрали хотя бы раз (несорванный кокос на дереве, ягоды на кусте, что-то только что появившееся из открытого багажа); их коллайдер отключён до этого момента, поэтому никакой физический луч (даже от {key:Item-Ping-Detection/enable-hit-assist}) не может в них попасть."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("УВІМКНУТИ ДОПОМОГУ ПРОМЕНЯ", "Також зараховує предмет/багаж як запінгований, якщо він достатньо близько до лінії прицілювання, повністю незалежно від фізики. Потрібно для предметів, які не можна штовхнути/зачепити, поки їх не підібрали хоча б раз (незірваний кокос на дереві, ягоди на кущі, щось щойно з'явлене з відкритого багажу); їхній колайдер вимкнено до цього моменту, тому жоден фізичний промінь (навіть від {key:Item-Ping-Detection/enable-hit-assist}) не може в них влучити."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("启用射线辅助", "如果物品/行李箱足够靠近你的瞄准线，也会将其算作被呼喊，完全独立于物理判定。适用于首次被拾取前无法推动/命中的物品（树上未采摘的椰子、灌木上的浆果、刚从打开的行李箱中生成的东西）；在此之前它们的碰撞体是禁用的，因此任何物理射线（即便是 {key:Item-Ping-Detection/enable-hit-assist} 的射线）都无法命中它们。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("啟用射線輔助", "如果物品/行李箱足夠靠近你的瞄準線，也會將其算作被呼喊，完全獨立於物理判定。適用於首次被撿起前無法推動/命中的物品（樹上未採摘的椰子、灌木上的漿果、剛從打開的行李箱中生成的東西）；在此之前它們的碰撞體是停用的，因此任何物理射線（即便是 {key:Item-Ping-Detection/enable-hit-assist} 的射線）都無法命中它們。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("光線アシストを有効化", "物理判定に一切依存せず、狙い線に十分近ければアイテム/荷物もピンされたとみなします。最初に拾われるまで押したり当てたりできないアイテム（木にまだ生えているココナッツ、茂みのベリー、開けた荷物から出現したばかりのもの）に必要です。それまではコライダーが無効なため、物理レイキャスト（{key:Item-Ping-Detection/enable-hit-assist} のものも含めて）では絶対に命中しません。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("광선 보조 활성화", "물리와 완전히 무관하게, 조준선에 충분히 가까우면 아이템/수하물도 핑된 것으로 간주합니다. 처음 주울 때까지 밀거나 맞힐 수 없는 아이템(나무에 달린 채취 전 코코넛, 덤불의 베리, 열린 수하물에서 갓 생성된 것 등)에 필요합니다. 그 전까지는 콜라이더가 비활성화되어 있어 어떤 물리 레이캐스트({key:Item-Ping-Detection/enable-hit-assist} 포함)도 명중시킬 수 없습니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("WŁĄCZ WSPOMAGANIE PROMIENIA", "Liczy przedmiot/bagaż jako zapingowany również wtedy, gdy jest wystarczająco blisko linii celowania, całkowicie niezależnie od fizyki. Potrzebne dla przedmiotów, których nie można popchnąć/trafić, dopóki nie zostaną podniesione po raz pierwszy (niezerwany kokos na drzewie, jagody na krzaku, coś świeżo pojawionego z otwartego bagażu); ich kolizja jest wyłączona do tego momentu, więc żaden fizyczny promień (nawet z {key:Item-Ping-Detection/enable-hit-assist}) nigdy w nie nie trafi."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("IŞIN YARDIMINI ETKİNLEŞTİR", "Fizikten tamamen bağımsız olarak, nişan hattınıza yeterince yakınsa bir eşyayı/bagajı da pinglenmiş sayar. İlk kez alınana kadar itilemeyen/vurulamayan eşyalar için gereklidir (ağaçtaki toplanmamış hindistan cevizi, çalıdaki meyveler, açılmış bir bagajdan yeni beliren bir şey); o ana kadar çarpışma alanları devre dışıdır, bu yüzden hiçbir fiziksel ışın ({key:Item-Ping-Detection/enable-hit-assist} bile) onlara asla isabet edemez."),
            });

            Add("ray-assist-radius-meters", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("RAY ASSIST RADIUS METERS", "Only used when {key:Item-Ping-Detection/enable-ray-assist} is on. How far off your exact aim line an item/luggage can be and still count as pinged."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("RAYON D'ASSISTANCE DE RAYON EN MÈTRES", "Utilisé uniquement si {key:Item-Ping-Detection/enable-ray-assist} est activé. À quelle distance de votre ligne de visée exacte un objet/bagage peut se trouver tout en comptant comme pingé."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("RAGGIO ASSISTENZA RAGGIO IN METRI", "Usato solo quando {key:Item-Ping-Detection/enable-ray-assist} è attivo. Quanto un oggetto/bagaglio può essere lontano dalla tua esatta linea di mira e contare comunque come pingato."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("STRAHLHILFE-RADIUS IN METERN", "Nur verwendet, wenn {key:Item-Ping-Detection/enable-ray-assist} aktiv ist. Wie weit ein Gegenstand/Gepäckstück von deiner exakten Ziellinie entfernt sein darf und trotzdem als angepingt zählt."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("RADIO DE ASISTENCIA DE RAYO EN METROS", "Solo se usa cuando {key:Item-Ping-Detection/enable-ray-assist} está activado. Cuánto puede alejarse un objeto/equipaje de tu línea de puntería exacta y seguir contando como pingado."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("RADIO DE ASISTENCIA DE RAYO EN METROS", "Solo se usa cuando {key:Item-Ping-Detection/enable-ray-assist} está activado. Cuánto puede alejarse un objeto/equipaje de tu línea de puntería exacta y seguir contando como pingado."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("RAIO DE ASSISTÊNCIA DE RAIO EM METROS", "Usado apenas quando {key:Item-Ping-Detection/enable-ray-assist} está ativado. O quão longe da sua linha de mira exata um item/bagagem pode estar e ainda contar como pingado."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("РАДИУС ПОМОЩИ ЛУЧА В МЕТРАХ", "Используется только при включённом {key:Item-Ping-Detection/enable-ray-assist}. Насколько далеко от вашей точной линии прицеливания может быть предмет/багаж и всё ещё считаться запингованным."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("РАДІУС ДОПОМОГИ ПРОМЕНЯ В МЕТРАХ", "Використовується лише коли увімкнено {key:Item-Ping-Detection/enable-ray-assist}. Наскільки далеко від вашої точної лінії прицілювання може бути предмет/багаж і все одно вважатися запінгованим."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("射线辅助半径（米）", "仅在 {key:Item-Ping-Detection/enable-ray-assist} 开启时生效。物品/行李箱与你精确瞄准线的偏离程度在此范围内时，仍会被算作被呼喊。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("射線輔助半徑（公尺）", "僅在 {key:Item-Ping-Detection/enable-ray-assist} 開啟時生效。物品/行李箱與你精確瞄準線的偏離程度在此範圍內時，仍會被算作被呼喊。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("光線アシスト半径（メートル）", "{key:Item-Ping-Detection/enable-ray-assist} が有効な場合のみ使用されます。正確な狙い線からどれだけ離れていてもアイテム/荷物がピンされたとみなされるかです。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("광선 보조 반경(미터)", "{key:Item-Ping-Detection/enable-ray-assist}가 켜져 있을 때만 사용됩니다. 정확한 조준선에서 얼마나 벗어나도 아이템/수하물이 핑된 것으로 간주되는지입니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("PROMIEŃ WSPOMAGANIA PROMIENIA W METRACH", "Używane tylko gdy {key:Item-Ping-Detection/enable-ray-assist} jest włączone. Jak daleko od dokładnej linii celowania może być przedmiot/bagaż i nadal liczyć się jako zapingowany."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("IŞIN YARDIMI YARIÇAPI (METRE)", "Yalnızca {key:Item-Ping-Detection/enable-ray-assist} açıkken kullanılır. Bir eşyanın/bagajın tam nişan hattınızdan ne kadar uzakta olup yine de pinglenmiş sayılabileceği."),
            });
        }
    }
}
