using System.Collections.Generic;

namespace SenseOfDirection.Ui.Localization.Config
{
    /// <summary>Localized names/descriptions for every "Pings" section config entry.</summary>
    internal static class PingsConfigLocalization
    {
        internal static void Register(ConfigLocalizationTable.Registry registry)
        {
            void Add(string key, Dictionary<LocalizedText.Language, ConfigLocalizationEntry> table) =>
                registry.Add("Pings", key, table);

            Add("remove-visibility-cutoff", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("REMOVE VISIBILITY CUTOFF", "Vanilla silently refuses to even spawn a ping's visual once its pinging player is more than ~40-50m from you. On by default so far pings still show up at all. Most of the other Pings settings only matter once this is on."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("SUPPRIMER LA LIMITE DE VISIBILITÉ", "Le jeu de base refuse silencieusement de générer le visuel d'un ping dès que le joueur qui l'envoie est à plus de ~40-50m de vous. Activé par défaut pour que les pings lointains s'affichent tout court. La plupart des autres réglages de Pings n'ont d'effet que si celui-ci est activé."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("RIMUOVI LIMITE DI VISIBILITÀ", "Il gioco base rifiuta silenziosamente di generare il visivo di un ping quando il giocatore che lo invia è a più di ~40-50m da te. Attivo di default, così i ping lontani vengono comunque mostrati. La maggior parte delle altre impostazioni di Pings conta solo se questa è attiva."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("SICHTBARKEITSGRENZE ENTFERNEN", "Vanilla verweigert stillschweigend das Erzeugen der Ping-Grafik, sobald der pingende Spieler mehr als ~40-50m entfernt ist. Standardmäßig aktiviert, damit weit entfernte Pings überhaupt angezeigt werden. Die meisten anderen Ping-Einstellungen wirken sich nur aus, wenn dies aktiviert ist."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("ELIMINAR LÍMITE DE VISIBILIDAD", "El juego base se niega silenciosamente a generar el efecto visual de un ping cuando el jugador que lo envía está a más de ~40-50m de ti. Activado por defecto para que los pings lejanos se muestren en absoluto. La mayoría de los demás ajustes de Pings solo importan si este está activado."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("ELIMINAR LÍMITE DE VISIBILIDAD", "El juego base se niega silenciosamente a generar el efecto visual de un ping cuando el jugador que lo envía está a más de ~40-50m de ti. Activado por defecto para que los pings lejanos se muestren siquiera. La mayoría de los demás ajustes de Pings solo importan si este está activado."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("REMOVER LIMITE DE VISIBILIDADE", "O jogo base se recusa silenciosamente a gerar o visual de um ping quando o jogador que o enviou está a mais de ~40-50m de você. Ativado por padrão para que pings distantes ao menos apareçam. A maioria das outras configurações de Pings só importa quando esta está ativada."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("УБРАТЬ ОГРАНИЧЕНИЕ ВИДИМОСТИ", "Ванильная игра молча отказывается создавать визуал пинга, если пингующий игрок находится дальше ~40-50м от вас. Включено по умолчанию, чтобы дальние пинги вообще отображались. Большинство других настроек Pings имеют смысл только при включённой этой опции."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("ПРИБРАТИ ОБМЕЖЕННЯ ВИДИМОСТІ", "Ванільна гра мовчки відмовляється створювати візуал пінгу, якщо гравець, який пінгує, перебуває далі ~40-50м від вас. Увімкнено за замовчуванням, щоб дальні пінги взагалі відображалися. Більшість інших налаштувань Pings мають значення лише за увімкненої цієї опції."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("移除可见距离限制", "原版游戏在发出呼喊的玩家距离你超过约40-50米时，会悄悄拒绝生成呼喊的视觉效果。默认开启，让远处的呼喊也能显示出来。本区大多数其他设置只有在此项开启时才起作用。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("移除可見距離限制", "原版遊戲在發出呼喊的玩家距離你超過約40-50公尺時，會悄悄拒絕產生呼喊的視覺效果。預設開啟，讓遠處的呼喊也能顯示出來。本區大多數其他設定只有在此項開啟時才會起作用。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("視認距離制限を解除", "バニラでは、ピンを送ったプレイヤーが約40～50m以上離れると、ピンの表示が黙って生成されなくなります。遠くのピンでもとにかく表示されるように、デフォルトで有効です。このセクションの他の設定のほとんどは、これが有効な場合にのみ意味を持ちます。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("가시 거리 제한 제거", "바닐라는 핑을 보낸 플레이어가 약 40~50m 이상 떨어지면 핑의 시각 효과 생성을 조용히 거부합니다. 먼 거리의 핑도 일단 표시되도록 기본적으로 켜져 있습니다. 이 섹션의 다른 설정 대부분은 이 옵션이 켜져 있을 때만 의미가 있습니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("USUŃ LIMIT WIDOCZNOŚCI", "Wersja podstawowa po cichu odmawia wygenerowania wizualizacji pingu, gdy pingujący gracz znajduje się dalej niż ~40-50m od ciebie. Domyślnie włączone, aby odległe pingi w ogóle się pojawiały. Większość pozostałych ustawień Pings ma znaczenie tylko wtedy, gdy ta opcja jest włączona."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("GÖRÜNÜRLÜK SINIRINI KALDIR", "Vanilla oyun, ping atan oyuncu sizden ~40-50m'den daha uzaktaysa pingin görselini sessizce oluşturmayı reddeder. Uzaktaki pinglerin en azından görünmesi için varsayılan olarak açıktır. Pings bölümündeki diğer ayarların çoğu yalnızca bu açıkken bir anlam ifade eder."),
            });

            Add("enable-scaling", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("ENABLE SCALING", "Scale ping visuals up the further away they are, well past vanilla's own hard-capped scale, so far pings stay easy to spot."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("ACTIVER LA MISE À L'ÉCHELLE", "Agrandit le visuel des pings à mesure qu'ils s'éloignent, bien au-delà de la limite fixe du jeu de base, pour que les pings lointains restent faciles à repérer."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("ATTIVA RIDIMENSIONAMENTO", "Ingrandisce il visivo dei ping più sono lontani, ben oltre il limite fisso del gioco base, così i ping distanti restano facili da individuare."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("SKALIERUNG AKTIVIEREN", "Vergrößert die Ping-Grafik mit zunehmender Entfernung, weit über die feste Obergrenze von Vanilla hinaus, damit weit entfernte Pings gut erkennbar bleiben."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("ACTIVAR ESCALADO", "Agranda el visual del ping cuanto más lejos está, muy por encima del límite fijo del juego base, para que los pings lejanos sigan siendo fáciles de ver."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("ACTIVAR ESCALADO", "Agranda el visual del ping cuanto más lejos está, muy por encima del límite fijo del juego base, para que los pings lejanos sigan siendo fáciles de ver."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("ATIVAR ESCALONAMENTO", "Aumenta o visual do ping quanto mais longe ele estiver, bem além do limite fixo do jogo base, para que pings distantes continuem fáceis de notar."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("ВКЛЮЧИТЬ МАСШТАБИРОВАНИЕ", "Увеличивает визуал пинга по мере удаления, значительно превышая жёсткий предел ванильной игры, чтобы дальние пинги оставалось легко заметить."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("УВІМКНУТИ МАСШТАБУВАННЯ", "Збільшує візуал пінгу зі збільшенням відстані, значно перевищуючи жорстку межу ванільної гри, щоб дальні пінги залишалося легко помітити."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("启用缩放", "让呼喊的视觉效果随距离变远而放大，远超原版固定上限，使远处的呼喊依然容易被发现。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("啟用縮放", "讓呼喊的視覺效果隨距離變遠而放大，遠超原版固定上限，使遠處的呼喊依然容易被發現。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("スケーリングを有効化", "バニラの固定上限を大きく超えて、遠くなるほどピンの表示を拡大し、遠くのピンでも見つけやすいままにします。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("크기 조정 활성화", "바닐라의 고정 상한을 훨씬 넘어서, 멀어질수록 핑의 시각 효과를 크게 만들어 먼 거리의 핑도 쉽게 눈에 띄게 합니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("WŁĄCZ SKALOWANIE", "Powiększa wizualizację pingu wraz z odległością, znacznie przekraczając sztywny limit wersji podstawowej, dzięki czemu odległe pingi łatwo zauważyć."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("ÖLÇEKLENDİRMEYİ ETKİNLEŞTİR", "Ping görselini uzaklaştıkça büyütür, vanilla oyunun sabit üst sınırının çok ötesine geçerek uzaktaki pinglerin de kolayca fark edilmesini sağlar."),
            });

            Add("scale-multiplier", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("SCALE MULTIPLIER", "Extra multiplier applied on top of vanilla's own (uncapped, see {key:Pings/remove-visibility-cutoff}) ping scale. 1x is vanilla's own uncapped size; higher makes every ping bigger regardless of distance."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("MULTIPLICATEUR D'ÉCHELLE", "Multiplicateur supplémentaire appliqué à l'échelle de ping du jeu de base (sans limite, voir {key:Pings/remove-visibility-cutoff}). 1x correspond à la taille non plafonnée du jeu de base ; une valeur plus élevée agrandit chaque ping quelle que soit la distance."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("MOLTIPLICATORE DI SCALA", "Moltiplicatore aggiuntivo applicato sopra la scala del ping del gioco base (senza limite, vedi {key:Pings/remove-visibility-cutoff}). 1x è la dimensione senza limite del gioco base; valori più alti ingrandiscono ogni ping indipendentemente dalla distanza."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("SKALIERUNGSMULTIPLIKATOR", "Zusätzlicher Multiplikator, der auf die (unbegrenzte, siehe {key:Pings/remove-visibility-cutoff}) Ping-Skalierung von Vanilla angewendet wird. 1x entspricht der unbegrenzten Vanilla-Größe; höhere Werte machen jeden Ping unabhängig von der Entfernung größer."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("MULTIPLICADOR DE ESCALA", "Multiplicador adicional aplicado sobre la escala de ping del juego base (sin límite, ver {key:Pings/remove-visibility-cutoff}). 1x es el tamaño sin límite del juego base; valores más altos agrandan cada ping sin importar la distancia."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("MULTIPLICADOR DE ESCALA", "Multiplicador adicional aplicado sobre la escala de ping del juego base (sin límite, ver {key:Pings/remove-visibility-cutoff}). 1x es el tamaño sin límite del juego base; valores más altos agrandan cada ping sin importar la distancia."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("MULTIPLICADOR DE ESCALA", "Multiplicador extra aplicado sobre a escala de ping do jogo base (sem limite, veja {key:Pings/remove-visibility-cutoff}). 1x é o tamanho sem limite do jogo base; valores maiores aumentam todo ping independentemente da distância."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("МНОЖИТЕЛЬ МАСШТАБА", "Дополнительный множитель, применяемый поверх собственного (без ограничений, см. {key:Pings/remove-visibility-cutoff}) масштаба пинга ванильной игры. 1x — это размер без ограничений ванильной игры; более высокие значения делают каждый пинг больше независимо от расстояния."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("МНОЖНИК МАСШТАБУ", "Додатковий множник, що застосовується поверх власного (без обмежень, див. {key:Pings/remove-visibility-cutoff}) масштабу пінгу ванільної гри. 1x — це розмір без обмежень ванільної гри; вищі значення роблять кожен пінг більшим незалежно від відстані."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("缩放倍率", "在原版自身（无上限，见 {key:Pings/remove-visibility-cutoff}）呼喊缩放基础上叠加的额外倍率。1x 即原版无上限的大小；数值越高，无论距离多远，每个呼喊都会显示得更大。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("縮放倍率", "在原版自身（無上限，見 {key:Pings/remove-visibility-cutoff}）呼喊縮放基礎上疊加的額外倍率。1x 即原版無上限的大小；數值越高，無論距離多遠，每個呼喊都會顯示得更大。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("スケール倍率", "バニラ本来の（上限なし、{key:Pings/remove-visibility-cutoff}参照）ピンのスケールにさらに掛け合わせる倍率です。1xはバニラの上限なしサイズそのもの。値を上げると距離に関係なくすべてのピンが大きくなります。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("크기 배율", "바닐라 자체(무제한, {key:Pings/remove-visibility-cutoff} 참고) 핑 크기 위에 추가로 곱해지는 배율입니다. 1x는 바닐라의 무제한 크기 그대로이며, 값이 높을수록 거리와 상관없이 모든 핑이 커집니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("MNOŻNIK SKALI", "Dodatkowy mnożnik nakładany na własną (bez limitu, patrz {key:Pings/remove-visibility-cutoff}) skalę pingu wersji podstawowej. 1x to rozmiar bez limitu z wersji podstawowej; wyższe wartości powiększają każdy ping niezależnie od odległości."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("ÖLÇEK ÇARPANI", "Vanilla oyunun kendi (sınırsız, bkz. {key:Pings/remove-visibility-cutoff}) ping ölçeğinin üzerine eklenen ek çarpan. 1x, vanilla'nın sınırsız boyutudur; daha yüksek değerler mesafeden bağımsız olarak her pingi büyütür."),
            });

            Add("enable-ripple", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("ENABLE RIPPLE", "Show an expanding ring in the pinging player's own character color at the ping location, so it reads against similarly-colored terrain."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("ACTIVER L'ONDE", "Affiche un anneau qui s'étend, de la couleur du personnage qui envoie le ping, à l'endroit du ping, pour qu'il reste visible sur un terrain de couleur similaire."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("ATTIVA ONDA", "Mostra un anello che si espande, del colore del personaggio che invia il ping, nel punto del ping, così resta visibile anche su un terreno di colore simile."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("WELLE AKTIVIEREN", "Zeigt am Ping-Ort einen sich ausbreitenden Ring in der Charakterfarbe des pingenden Spielers, damit er auch auf ähnlich gefärbtem Gelände erkennbar bleibt."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("ACTIVAR ONDA", "Muestra un anillo que se expande, con el color del personaje que envía el ping, en el lugar del ping, para que se distinga sobre un terreno de color similar."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("ACTIVAR ONDA", "Muestra un anillo que se expande, con el color del personaje que envía el ping, en el lugar del ping, para que se distinga sobre un terreno de color similar."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("ATIVAR ONDULAÇÃO", "Mostra um anel em expansão, na cor do personagem que enviou o ping, no local do ping, para que ele se destaque mesmo em terrenos de cor parecida."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("ВКЛЮЧИТЬ РЯБЬ", "Показывает расширяющееся кольцо цвета персонажа пингующего игрока в месте пинга, чтобы его было видно даже на местности похожего цвета."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("УВІМКНУТИ ХВИЛЮ", "Показує кільце, що розширюється, кольору персонажа гравця, який пінгує, у місці пінгу, щоб його було видно навіть на місцевості схожого кольору."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("启用涟漪", "在呼喊位置显示一个以发出呼喊玩家角色颜色扩散的圆环，即使在颜色相近的地形上也能看清。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("啟用漣漪", "在呼喊位置顯示一個以發出呼喊玩家角色顏色擴散的圓環，即使在顏色相近的地形上也能看清。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("波紋を有効化", "ピンを送ったプレイヤーのキャラクターカラーで広がるリングをピンの位置に表示し、似た色の地形でも見分けやすくします。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("물결 효과 활성화", "핑을 보낸 플레이어의 캐릭터 색상으로 퍼져나가는 원을 핑 위치에 표시하여 비슷한 색의 지형에서도 잘 보이게 합니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("WŁĄCZ FALĘ", "Pokazuje rozszerzający się pierścień w kolorze postaci gracza wysyłającego pinga w miejscu pingu, dzięki czemu jest widoczny nawet na podobnie ukolorowionym terenie."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("DALGAYI ETKİNLEŞTİR", "Ping konumunda, ping atan oyuncunun karakter rengiyle genişleyen bir halka gösterir; böylece benzer renkli bir zeminde bile fark edilir."),
            });

            Add("enable-offscreen-indicator", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("ENABLE OFFSCREEN INDICATOR", "Show an edge-of-screen arrow pointing toward an active ping when it's off-screen, same mechanism as the player-label/campfire indicators. Only the arrow; the distance line below is {key:Pings/show-distance}'s own call. Moot while {key:General/ping-placement} is {enumval:IndicatorPlacement.CompassOnly}, which hides the whole edge-of-screen widget anyway."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("ACTIVER L'INDICATEUR HORS ÉCRAN", "Affiche une flèche en bord d'écran pointant vers un ping actif lorsqu'il est hors champ, même mécanisme que les indicateurs de label joueur/feu de camp. Seulement la flèche ; la ligne de distance en dessous dépend de {key:Pings/show-distance}. Sans effet si {key:General/ping-placement} est réglé sur {enumval:IndicatorPlacement.CompassOnly}, qui masque de toute façon tout le widget de bord d'écran."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("ATTIVA INDICATORE FUORI SCHERMO", "Mostra una freccia sul bordo dello schermo che punta verso un ping attivo quando è fuori vista, stesso meccanismo degli indicatori di etichetta giocatore/falò. Solo la freccia; la riga della distanza sotto dipende da {key:Pings/show-distance}. Ininfluente se {key:General/ping-placement} è impostato su {enumval:IndicatorPlacement.CompassOnly}, che nasconde comunque l'intero widget sul bordo dello schermo."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("BILDSCHIRMRAND-ANZEIGE AKTIVIEREN", "Zeigt einen Pfeil am Bildschirmrand, der auf einen aktiven Ping zeigt, wenn er außerhalb des Bildschirms ist - gleicher Mechanismus wie bei den Spieler-Label-/Lagerfeuer-Anzeigen. Nur der Pfeil; die Entfernungszeile darunter hängt von {key:Pings/show-distance} ab. Wirkungslos, solange {key:General/ping-placement} auf {enumval:IndicatorPlacement.CompassOnly} steht, was das ganze Bildschirmrand-Widget ohnehin ausblendet."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("ACTIVAR INDICADOR FUERA DE PANTALLA", "Muestra una flecha en el borde de la pantalla que señala un ping activo cuando está fuera de vista, el mismo mecanismo que los indicadores de etiqueta de jugador/hoguera. Solo la flecha; la línea de distancia debajo depende de {key:Pings/show-distance}. Sin efecto si {key:General/ping-placement} está en {enumval:IndicatorPlacement.CompassOnly}, que oculta todo el widget de borde de pantalla de todos modos."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("ACTIVAR INDICADOR FUERA DE PANTALLA", "Muestra una flecha en el borde de la pantalla que señala un ping activo cuando está fuera de vista, el mismo mecanismo que los indicadores de etiqueta de jugador/fogata. Solo la flecha; la línea de distancia debajo depende de {key:Pings/show-distance}. Sin efecto si {key:General/ping-placement} está en {enumval:IndicatorPlacement.CompassOnly}, que oculta todo el widget de borde de pantalla de todos modos."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("ATIVAR INDICADOR FORA DA TELA", "Mostra uma seta na borda da tela apontando para um ping ativo quando ele está fora de vista, mesmo mecanismo dos indicadores de rótulo de jogador/fogueira. Só a seta; a linha de distância abaixo depende de {key:Pings/show-distance}. Sem efeito enquanto {key:General/ping-placement} estiver como {enumval:IndicatorPlacement.CompassOnly}, que oculta todo o widget de borda da tela de qualquer forma."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("ВКЛЮЧИТЬ ИНДИКАТОР ЗА ЭКРАНОМ", "Показывает стрелку на краю экрана, указывающую на активный пинг, когда он вне поля зрения - тот же механизм, что и у меток игроков/индикатора костра. Только стрелка; строка расстояния ниже зависит от {key:Pings/show-distance}. Не имеет значения, если {key:General/ping-placement} установлено в {enumval:IndicatorPlacement.CompassOnly}, что всё равно скрывает весь виджет на краю экрана."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("УВІМКНУТИ ІНДИКАТОР ЗА ЕКРАНОМ", "Показує стрілку на краю екрана, що вказує на активний пінг, коли він поза полем зору - той самий механізм, що й у міток гравців/індикатора багаття. Лише стрілка; рядок відстані нижче залежить від {key:Pings/show-distance}. Не має значення, якщо {key:General/ping-placement} встановлено на {enumval:IndicatorPlacement.CompassOnly}, що все одно приховує весь віджет на краю екрана."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("启用屏幕外指示器", "当有效呼喊在屏幕外时，在屏幕边缘显示一个指向它的箭头，机制与玩家标签/篝火指示器相同。仅箭头本身；下方的距离行由 {key:Pings/show-distance} 决定。若 {key:General/ping-placement} 设为 {enumval:IndicatorPlacement.CompassOnly}，此项无意义，因为整个屏幕边缘控件都会被隐藏。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("啟用螢幕外指示器", "當有效呼喊在螢幕外時，在螢幕邊緣顯示一個指向它的箭頭，機制與玩家標籤/營火指示器相同。僅箭頭本身；下方的距離行由 {key:Pings/show-distance} 決定。若 {key:General/ping-placement} 設為 {enumval:IndicatorPlacement.CompassOnly}，此項無意義，因為整個螢幕邊緣元件都會被隱藏。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("画面外インジケーターを有効化", "有効なピンが画面外にあるとき、画面端にそれを指す矢印を表示します。プレイヤーラベルや焚き火インジケーターと同じ仕組みです。矢印のみで、下の距離行は{key:Pings/show-distance}の設定次第です。{key:General/ping-placement}が{enumval:IndicatorPlacement.CompassOnly}の場合、画面端ウィジェット自体が非表示になるため無意味です。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("화면 밖 표시기 활성화", "활성 핑이 화면 밖에 있을 때 화면 가장자리에 이를 가리키는 화살표를 표시합니다. 플레이어 라벨/모닥불 표시기와 동일한 방식입니다. 화살표만 해당하며, 아래 거리 줄은 {key:Pings/show-distance} 설정을 따릅니다. {key:General/ping-placement}가 {enumval:IndicatorPlacement.CompassOnly}면 화면 가장자리 요소 전체가 숨겨지므로 의미가 없습니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("WŁĄCZ WSKAŹNIK POZA EKRANEM", "Pokazuje strzałkę na krawędzi ekranu wskazującą aktywnego pinga, gdy jest poza ekranem - ten sam mechanizm co wskaźniki etykiet graczy/ogniska. Tylko strzałka; linia odległości poniżej zależy od {key:Pings/show-distance}. Bez znaczenia, gdy {key:General/ping-placement} to {enumval:IndicatorPlacement.CompassOnly}, co i tak ukrywa cały widżet na krawędzi ekranu."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("EKRAN DIŞI GÖSTERGEYİ ETKİNLEŞTİR", "Aktif bir ping ekran dışındayken ekran kenarında ona işaret eden bir ok gösterir; oyuncu etiketi/kamp ateşi göstergeleriyle aynı mekanizma. Sadece ok; alttaki mesafe satırı {key:Pings/show-distance} ayarına bağlıdır. {key:General/ping-placement} {enumval:IndicatorPlacement.CompassOnly} iken zaten tüm ekran kenarı bileşenini gizlediği için anlamsızdır."),
            });

            Add("show-distance", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("SHOW DISTANCE", "Show a distance sub-line under the ping indicator."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("AFFICHER LA DISTANCE", "Affiche une sous-ligne de distance sous l'indicateur de ping."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("MOSTRA DISTANZA", "Mostra una sottolinea della distanza sotto l'indicatore del ping."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("ENTFERNUNG ANZEIGEN", "Zeigt eine Entfernungszeile unter der Ping-Anzeige."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("MOSTRAR DISTANCIA", "Muestra una línea de distancia debajo del indicador de ping."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("MOSTRAR DISTANCIA", "Muestra una línea de distancia debajo del indicador de ping."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("MOSTRAR DISTÂNCIA", "Mostra uma linha de distância abaixo do indicador de ping."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("ПОКАЗЫВАТЬ РАССТОЯНИЕ", "Показывает строку расстояния под индикатором пинга."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("ПОКАЗУВАТИ ВІДСТАНЬ", "Показує рядок відстані під індикатором пінгу."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("显示距离", "在呼喊指示器下方显示距离子行。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("顯示距離", "在呼喊指示器下方顯示距離子行。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("距離を表示", "ピンインジケーターの下に距離のサブ行を表示します。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("거리 표시", "핑 표시기 아래에 거리 보조 줄을 표시합니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("POKAŻ ODLEGŁOŚĆ", "Pokazuje linię odległości pod wskaźnikiem pingu."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("MESAFEYİ GÖSTER", "Ping göstergesinin altında mesafe alt satırını gösterir."),
            });

            Add("enable-ghost-ping", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("ENABLE GHOST PING", "Let dead players keep pinging as ghosts (vanilla blocks pinging once dead), colored using their own character color same as when alive. Requires both sides to have this mod installed."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("ACTIVER LE PING FANTÔME", "Permet aux joueurs morts de continuer à envoyer des pings en tant que fantômes (le jeu de base bloque les pings après la mort), avec la couleur de leur personnage comme de leur vivant. Nécessite que ce mod soit installé des deux côtés."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("ATTIVA PING FANTASMA", "Permette ai giocatori morti di continuare a inviare ping da fantasmi (il gioco base blocca i ping dopo la morte), usando lo stesso colore del personaggio di quando erano vivi. Richiede che questo mod sia installato su entrambi i lati."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("GEISTER-PING AKTIVIEREN", "Lässt tote Spieler als Geister weiter pingen (Vanilla blockiert Pings nach dem Tod), in derselben Charakterfarbe wie zu Lebzeiten. Erfordert, dass dieser Mod bei beiden Seiten installiert ist."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("ACTIVAR PING FANTASMA", "Permite que los jugadores muertos sigan enviando pings como fantasmas (el juego base bloquea los pings tras morir), con el mismo color de personaje que en vida. Requiere que este mod esté instalado en ambos lados."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("ACTIVAR PING FANTASMA", "Permite que los jugadores muertos sigan enviando pings como fantasmas (el juego base bloquea los pings tras morir), con el mismo color de personaje que en vida. Requiere que este mod esté instalado en ambos lados."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("ATIVAR PING FANTASMA", "Permite que jogadores mortos continuem enviando pings como fantasmas (o jogo base bloqueia pings após a morte), usando a mesma cor de personagem de quando vivos. Requer que este mod esteja instalado nos dois lados."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("ВКЛЮЧИТЬ ПИНГ ПРИЗРАКА", "Позволяет мёртвым игрокам продолжать пинговать в виде призраков (ванильная игра блокирует пинги после смерти), с тем же цветом персонажа, что и при жизни. Требует, чтобы мод был установлен у обеих сторон."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("УВІМКНУТИ ПІНГ ПРИВИДА", "Дозволяє мертвим гравцям продовжувати пінгувати у вигляді привидів (ванільна гра блокує пінги після смерті), з тим самим кольором персонажа, що й за життя. Потребує, щоб мод було встановлено в обох сторін."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("启用幽灵呼喊", "允许死亡玩家以幽灵身份继续呼喊（原版在死亡后会禁止呼喊），颜色与生前使用的角色颜色相同。需要双方都安装此模组。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("啟用幽靈呼喊", "允許死亡玩家以幽靈身分繼續呼喊（原版在死亡後會禁止呼喊），顏色與生前使用的角色顏色相同。需要雙方都安裝此模組。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("ゴーストピングを有効化", "死亡したプレイヤーが幽霊状態でもピンを送り続けられるようにします（バニラでは死亡後はピン不可）。色は生前と同じキャラクターカラーです。双方にこのMODが導入されている必要があります。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("유령 핑 활성화", "사망한 플레이어가 유령 상태에서도 계속 핑을 보낼 수 있게 합니다(바닐라는 사망 후 핑을 막습니다). 색상은 생전과 동일한 캐릭터 색상을 사용합니다. 양쪽 모두 이 모드가 설치되어 있어야 합니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("WŁĄCZ PINGOWANIE JAKO DUCH", "Pozwala martwym graczom nadal pingować jako duchy (wersja podstawowa blokuje pingowanie po śmierci), w tym samym kolorze postaci co za życia. Wymaga zainstalowania tego moda po obu stronach."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("HAYALET PİNGİNİ ETKİNLEŞTİR", "Ölü oyuncuların hayalet olarak ping atmaya devam etmesine izin verir (vanilla oyun ölümden sonra ping atmayı engeller), hayattayken kullandıkları karakter rengiyle. Bu modun her iki tarafta da kurulu olmasını gerektirir."),
            });
        }
    }
}
