using System.Collections.Generic;

namespace SenseOfDirection.Ui.Localization.Config
{
    /// <summary>Localized names/descriptions for every "Ping-Anti-Spam" section config entry.</summary>
    internal static class PingAntiSpamConfigLocalization
    {
        internal static void Register(ConfigLocalizationTable.Registry registry)
        {
            void Add(string key, Dictionary<LocalizedText.Language, ConfigLocalizationEntry> table) =>
                registry.Add("Ping-Anti-Spam", key, table);

            Add("enable-anti-spam", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("ENABLE ANTI-SPAM", "Rate-limits how often *other* players' pings actually render/play once they're pinging rapidly, so spamming the ping key isn't more disruptive than vanilla now that pings are bigger/louder. A short burst always goes through instantly; only once someone keeps spamming does \"slow mode\" kick in, queueing further pings to arrive at a throttled rate instead (never silently dropped, unless the queue itself is full; see {key:Ping-Anti-Spam/max-queue-length}). Never applies to your own pings."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("ACTIVER L'ANTI-SPAM", "Limite la fréquence à laquelle les pings des *autres* joueurs s'affichent/se jouent réellement lorsqu'ils pingent rapidement, pour que spammer la touche de ping ne soit pas plus gênant que dans le jeu de base maintenant que les pings sont plus grands/plus forts. Une courte rafale passe toujours instantanément ; ce n'est que si quelqu'un continue de spammer que le « mode lent » se déclenche, mettant les pings suivants en file d'attente à un rythme réduit (jamais supprimés silencieusement, sauf si la file est pleine ; voir {key:Ping-Anti-Spam/max-queue-length}). Ne s'applique jamais à vos propres pings."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("ATTIVA ANTI-SPAM", "Limita la frequenza con cui i ping degli *altri* giocatori vengono effettivamente mostrati/riprodotti quando pingano rapidamente, così spammare il tasto ping non è più fastidioso che nel gioco base ora che i ping sono più grandi/rumorosi. Una breve raffica passa sempre subito; solo se qualcuno continua a spammare entra in azione la \"modalità lenta\", mettendo in coda i ping successivi a un ritmo limitato (mai eliminati silenziosamente, a meno che la coda non sia piena; vedi {key:Ping-Anti-Spam/max-queue-length}). Non si applica mai ai tuoi ping."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("ANTI-SPAM AKTIVIEREN", "Begrenzt, wie oft die Pings *anderer* Spieler tatsächlich gerendert/abgespielt werden, wenn diese schnell hintereinander pingen, damit das Spammen der Ping-Taste nicht störender ist als in Vanilla, jetzt wo Pings größer/lauter sind. Ein kurzer Schwall geht immer sofort durch; erst wenn jemand weiter spammt, greift der „Slow Mode“, der weitere Pings gedrosselt nacheinander eintreffen lässt (nie stillschweigend verworfen, außer die Warteschlange ist voll; siehe {key:Ping-Anti-Spam/max-queue-length}). Gilt nie für deine eigenen Pings."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("ACTIVAR ANTI-SPAM", "Limita la frecuencia con la que se renderizan/reproducen realmente los pings de *otros* jugadores cuando pingan rápidamente, para que spamear la tecla de ping no sea más molesto que en el juego base ahora que los pings son más grandes/ruidosos. Una ráfaga corta siempre pasa al instante; solo si alguien sigue spameando se activa el «modo lento», que pone en cola los siguientes pings a un ritmo limitado (nunca se descartan en silencio, salvo que la cola esté llena; ver {key:Ping-Anti-Spam/max-queue-length}). Nunca se aplica a tus propios pings."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("ACTIVAR ANTI-SPAM", "Limita la frecuencia con la que se renderizan/reproducen realmente los pings de *otros* jugadores cuando pingan rápidamente, para que spamear la tecla de ping no sea más molesto que en el juego base ahora que los pings son más grandes/ruidosos. Una ráfaga corta siempre pasa al instante; solo si alguien sigue spameando se activa el «modo lento», que pone en cola los siguientes pings a un ritmo limitado (nunca se descartan en silencio, salvo que la cola esté llena; ver {key:Ping-Anti-Spam/max-queue-length}). Nunca se aplica a tus propios pings."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("ATIVAR ANTI-SPAM", "Limita a frequência com que os pings de *outros* jogadores são realmente renderizados/tocados quando eles pingam rapidamente, para que abusar da tecla de ping não seja mais incômodo que no jogo base agora que os pings são maiores/mais altos. Uma sequência curta sempre passa na hora; só quando alguém continua abusando é que o \"modo lento\" entra em ação, colocando os pings seguintes em fila a um ritmo reduzido (nunca descartados silenciosamente, a menos que a fila esteja cheia; veja {key:Ping-Anti-Spam/max-queue-length}). Nunca se aplica aos seus próprios pings."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("ВКЛЮЧИТЬ ЗАЩИТУ ОТ СПАМА", "Ограничивает, как часто пинги *других* игроков реально отображаются/проигрываются, когда те пингуют часто, чтобы спам кнопкой пинга не был раздражающим сильнее, чем в ванильной игре теперь, когда пинги стали крупнее/громче. Короткая серия всегда проходит мгновенно; только когда кто-то продолжает спамить, включается «медленный режим», ставя дальнейшие пинги в очередь с ограниченной скоростью (никогда не отбрасываются молча, если только очередь не заполнена; см. {key:Ping-Anti-Spam/max-queue-length}). Никогда не применяется к вашим собственным пингам."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("УВІМКНУТИ ЗАХИСТ ВІД СПАМУ", "Обмежує, як часто пінги *інших* гравців реально відображаються/відтворюються, коли ті пінгують часто, щоб спам кнопкою пінгу не дратував більше, ніж у ванільній грі тепер, коли пінги стали більшими/гучнішими. Коротка серія завжди проходить миттєво; лише коли хтось продовжує спамити, вмикається «повільний режим», ставлячи подальші пінги в чергу з обмеженою швидкістю (ніколи не відкидаються мовчки, хіба що черга заповнена; див. {key:Ping-Anti-Spam/max-queue-length}). Ніколи не застосовується до ваших власних пінгів."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("启用防刷屏", "限制*其他*玩家在快速连续呼喊时实际渲染/播放的频率，这样在呼喊变得更大更响之后，狂按呼喊键也不会比原版更烦人。短促的连续呼喊总是立即通过；只有当某人持续刷屏时才会触发“慢速模式”，让后续呼喊按限速排队显示（除非队列已满，否则绝不会被静默丢弃；见 {key:Ping-Anti-Spam/max-queue-length}）。此设置从不影响你自己发出的呼喊。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("啟用防洗版", "限制*其他*玩家在快速連續呼喊時實際渲染/播放的頻率，這樣在呼喊變得更大更響之後，狂按呼喊鍵也不會比原版更煩人。短促的連續呼喊總是立即通過；只有當某人持續洗版時才會觸發「慢速模式」，讓後續呼喊按限速排隊顯示（除非佇列已滿，否則絕不會被靜默丟棄；見 {key:Ping-Anti-Spam/max-queue-length}）。此設定從不影響你自己發出的呼喊。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("アンチスパムを有効化", "*他の*プレイヤーが連続でピンを送っているとき、実際に表示/再生される頻度を制限します。ピンが大きく/うるさくなった今、ピンキー連打がバニラより邪魔にならないようにするためです。短いバーストは常に即座に通ります。誰かがスパムを続けた場合のみ「スロー モード」が発動し、以降のピンは制限された間隔でキューに入れて表示されます（キューが満杯でない限り、無言で破棄されることはありません。{key:Ping-Anti-Spam/max-queue-length}参照）。自分自身のピンには決して適用されません。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("도배 방지 활성화", "*다른* 플레이어가 빠르게 핑을 연타할 때 실제로 렌더링/재생되는 빈도를 제한하여, 핑이 더 커지고 시끄러워진 지금 핑 키 도배가 바닐라보다 더 거슬리지 않게 합니다. 짧은 연속 핑은 항상 즉시 통과합니다. 누군가 계속 도배할 때만 \"슬로우 모드\"가 발동해 이후 핑을 제한된 속도로 대기열에 넣어 표시합니다(대기열이 가득 차지 않는 한 조용히 버려지지 않습니다. {key:Ping-Anti-Spam/max-queue-length} 참고). 자신의 핑에는 절대 적용되지 않습니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("WŁĄCZ OCHRONĘ PRZED SPAMEM", "Ogranicza, jak często pingi *innych* graczy są faktycznie renderowane/odtwarzane, gdy pingują szybko, aby spamowanie klawiszem pinga nie było bardziej uciążliwe niż w wersji podstawowej, teraz gdy pingi są większe/głośniejsze. Krótka seria zawsze przechodzi natychmiast; dopiero gdy ktoś dalej spamuje, włącza się „tryb spowolniony”, kolejkując kolejne pingi w ograniczonym tempie (nigdy nie są po cichu odrzucane, chyba że kolejka jest pełna; patrz {key:Ping-Anti-Spam/max-queue-length}). Nigdy nie dotyczy twoich własnych pingów."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("SPAM ÖNLEMEYİ ETKİNLEŞTİR", "*Diğer* oyuncuların hızlı ping atması durumunda pinglerinin gerçekten ne sıklıkla işlenip/çalınacağını sınırlar; böylece pingler artık daha büyük/yüksek sesli olduğu için ping tuşuna basıp durmak vanilladan daha rahatsız edici olmaz. Kısa bir patlama her zaman anında geçer; yalnızca biri spam yapmaya devam ederse \"yavaş mod\" devreye girer ve sonraki pingleri sınırlı bir hızda kuyruğa alır (kuyruk dolu olmadıkça asla sessizce atılmaz; bkz. {key:Ping-Anti-Spam/max-queue-length}). Kendi pinglerinize asla uygulanmaz."),
            });

            Add("free-spam-count", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("FREE SPAM COUNT", "How many pings in a row from the same player always show up instantly before slow mode kicks in."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("NOMBRE DE PINGS LIBRES", "Combien de pings consécutifs d'un même joueur s'affichent toujours instantanément avant que le mode lent ne se déclenche."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("CONTEGGIO PING LIBERI", "Quanti ping consecutivi dello stesso giocatore vengono sempre mostrati subito prima che scatti la modalità lenta."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("ANZAHL FREIER PINGS", "Wie viele aufeinanderfolgende Pings desselben Spielers immer sofort angezeigt werden, bevor der Slow Mode einsetzt."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("CANTIDAD DE PINGS LIBRES", "Cuántos pings seguidos del mismo jugador se muestran siempre al instante antes de que se active el modo lento."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("CANTIDAD DE PINGS LIBRES", "Cuántos pings seguidos del mismo jugador se muestran siempre al instante antes de que se active el modo lento."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("CONTAGEM DE PINGS LIVRES", "Quantos pings seguidos do mesmo jogador sempre aparecem instantaneamente antes do modo lento entrar em ação."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("КОЛИЧЕСТВО СВОБОДНЫХ ПИНГОВ", "Сколько пингов подряд от одного игрока всегда отображаются мгновенно, прежде чем включится медленный режим."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("КІЛЬКІСТЬ ВІЛЬНИХ ПІНГІВ", "Скільки пінгів поспіль від одного гравця завжди відображаються миттєво, перш ніж увімкнеться повільний режим."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("免费呼喊次数", "同一玩家连续发出多少次呼喊会一直立即显示，超过后才触发慢速模式。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("免費呼喊次數", "同一玩家連續發出多少次呼喊會一直立即顯示，超過後才觸發慢速模式。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("フリースパム回数", "同じプレイヤーからの連続ピンが何回まで常に即座に表示されるか（これを超えるとスロー モードが発動）。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("무료 연타 횟수", "슬로우 모드가 발동하기 전, 같은 플레이어의 연속 핑이 항상 즉시 표시되는 횟수입니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("LICZBA WOLNYCH PINGÓW", "Ile pingów z rzędu od tego samego gracza zawsze pojawia się natychmiast, zanim włączy się tryb spowolniony."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("SERBEST PING SAYISI", "Yavaş mod devreye girmeden önce aynı oyuncudan art arda kaç pingin her zaman anında görüneceği."),
            });

            Add("slow-mode-interval-seconds", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("SLOW MODE INTERVAL SECONDS", "Once slow mode kicks in, queued pings from that player are spaced at least this far apart before they're actually shown to you."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("INTERVALLE DU MODE LENT (SECONDES)", "Une fois le mode lent déclenché, les pings en file d'attente de ce joueur sont espacés d'au moins cette durée avant de vous être réellement montrés."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("INTERVALLO MODALITÀ LENTA (SECONDI)", "Una volta attivata la modalità lenta, i ping in coda di quel giocatore sono distanziati di almeno questo intervallo prima di esserti effettivamente mostrati."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("SLOW-MODE-INTERVALL IN SEKUNDEN", "Sobald der Slow Mode einsetzt, werden die in der Warteschlange befindlichen Pings dieses Spielers um mindestens diesen Abstand getrennt, bevor sie dir tatsächlich angezeigt werden."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("INTERVALO DE MODO LENTO EN SEGUNDOS", "Una vez activado el modo lento, los pings en cola de ese jugador se espacian al menos este tiempo antes de mostrártelos de verdad."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("INTERVALO DE MODO LENTO EN SEGUNDOS", "Una vez activado el modo lento, los pings en cola de ese jugador se espacian al menos este tiempo antes de mostrártelos de verdad."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("INTERVALO DO MODO LENTO EM SEGUNDOS", "Assim que o modo lento entra em ação, os pings na fila daquele jogador são espaçados em pelo menos esse intervalo antes de serem realmente mostrados a você."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("ИНТЕРВАЛ МЕДЛЕННОГО РЕЖИМА (СЕК.)", "Как только включается медленный режим, пинги этого игрока в очереди разделяются минимум этим интервалом, прежде чем реально показываются вам."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("ІНТЕРВАЛ ПОВІЛЬНОГО РЕЖИМУ (СЕК.)", "Щойно вмикається повільний режим, пінги цього гравця в черзі розділяються щонайменше цим інтервалом, перш ніж реально показуються вам."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("慢速模式间隔（秒）", "一旦进入慢速模式，该玩家排队中的呼喊之间至少间隔这么长时间才会真正显示给你。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("慢速模式間隔（秒）", "一旦進入慢速模式，該玩家排隊中的呼喊之間至少間隔這麼長時間才會真正顯示給你。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("スロー モード間隔（秒）", "スロー モードが発動すると、そのプレイヤーのキュー内のピンは、実際に表示されるまで少なくともこの間隔が空けられます。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("슬로우 모드 간격(초)", "슬로우 모드가 발동하면, 해당 플레이어의 대기열에 있는 핑들은 실제로 표시되기까지 최소 이 간격만큼 떨어집니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("ODSTĘP TRYBU SPOWOLNIONEGO (SEK.)", "Gdy włączy się tryb spowolniony, kolejkowane pingi tego gracza są rozdzielone co najmniej tym odstępem, zanim faktycznie zostaną ci pokazane."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("YAVAŞ MOD ARALIĞI (SANİYE)", "Yavaş mod devreye girdiğinde, o oyuncunun kuyruktaki pingleri size gerçekten gösterilmeden önce en az bu kadar aralıklarla sıralanır."),
            });

            Add("max-queue-length", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("MAX QUEUE LENGTH", "How many of a spamming player's pings can be queued up waiting to show at once while in slow mode. Any further ping while the queue's already full is dropped entirely rather than queued."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("LONGUEUR MAXIMALE DE LA FILE", "Combien de pings d'un joueur en train de spammer peuvent être mis en file d'attente à la fois en mode lent. Tout ping supplémentaire alors que la file est déjà pleine est purement ignoré plutôt que mis en attente."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("LUNGHEZZA MASSIMA CODA", "Quanti ping di un giocatore che spamma possono essere messi in coda contemporaneamente in modalità lenta. Ogni ulteriore ping mentre la coda è già piena viene ignorato del tutto anziché accodato."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("MAXIMALE WARTESCHLANGENLÄNGE", "Wie viele Pings eines spammenden Spielers im Slow Mode gleichzeitig in der Warteschlange auf ihre Anzeige warten können. Jeder weitere Ping bei bereits voller Warteschlange wird komplett verworfen statt eingereiht."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("LONGITUD MÁXIMA DE COLA", "Cuántos pings de un jugador que hace spam pueden ponerse en cola a la vez en modo lento. Cualquier ping adicional mientras la cola ya está llena se descarta por completo en lugar de encolarse."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("LONGITUD MÁXIMA DE COLA", "Cuántos pings de un jugador que hace spam pueden ponerse en cola a la vez en modo lento. Cualquier ping adicional mientras la cola ya está llena se descarta por completo en lugar de encolarse."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("TAMANHO MÁXIMO DA FILA", "Quantos pings de um jogador que está abusando podem ficar na fila esperando para aparecer de uma vez em modo lento. Qualquer ping extra enquanto a fila já está cheia é totalmente descartado em vez de enfileirado."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("МАКСИМАЛЬНАЯ ДЛИНА ОЧЕРЕДИ", "Сколько пингов спамящего игрока может одновременно стоять в очереди на показ в медленном режиме. Любой дополнительный пинг при уже заполненной очереди полностью отбрасывается, а не встаёт в очередь."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("МАКСИМАЛЬНА ДОВЖИНА ЧЕРГИ", "Скільки пінгів гравця, що спамить, може одночасно стояти в черзі на показ у повільному режимі. Будь-який додатковий пінг за вже заповненої черги повністю відкидається, а не стає в чергу."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("最大队列长度", "在慢速模式下，某个刷屏玩家的呼喊最多可以有多少条同时排队等待显示。当队列已满时，再多的呼喊会被直接丢弃，而不是继续排队。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("最大佇列長度", "在慢速模式下，某個洗版玩家的呼喊最多可以有多少條同時排隊等待顯示。當佇列已滿時，再多的呼喊會被直接丟棄，而不是繼續排隊。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("最大キュー長", "スロー モード中、スパムしているプレイヤーのピンを同時に何件までキューで待たせられるか。キューが満杯のときにさらにピンが来ると、キューに入れず完全に破棄されます。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("최대 대기열 길이", "슬로우 모드에서 도배 중인 플레이어의 핑을 한 번에 몇 개까지 대기열에 쌓아둘 수 있는지입니다. 대기열이 이미 가득 찬 상태에서 추가로 오는 핑은 대기열에 넣지 않고 완전히 버립니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("MAKSYMALNA DŁUGOŚĆ KOLEJKI", "Ile pingów spamującego gracza może jednocześnie czekać w kolejce na pokazanie w trybie spowolnionym. Każdy kolejny ping, gdy kolejka jest już pełna, jest całkowicie odrzucany zamiast kolejkowany."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("MAKSİMUM KUYRUK UZUNLUĞU", "Yavaş moddayken spam yapan bir oyuncunun aynı anda kaç pinginin gösterilmek üzere kuyrukta bekleyebileceği. Kuyruk zaten doluyken gelen herhangi bir ping kuyruğa alınmak yerine tamamen atılır."),
            });

            Add("reset-seconds", new Dictionary<LocalizedText.Language, ConfigLocalizationEntry>
            {
                [LocalizedText.Language.English] = new ConfigLocalizationEntry("RESET SECONDS", "How long a player has to go without pinging (with their queue fully drained) before slow mode fully resets to normal."),
                [LocalizedText.Language.French] = new ConfigLocalizationEntry("SECONDES AVANT RÉINITIALISATION", "Combien de temps un joueur doit rester sans pinger (avec sa file entièrement vidée) avant que le mode lent ne revienne complètement à la normale."),
                [LocalizedText.Language.Italian] = new ConfigLocalizationEntry("SECONDI DI RIPRISTINO", "Per quanto tempo un giocatore deve stare senza pingare (con la coda completamente svuotata) prima che la modalità lenta si ripristini del tutto."),
                [LocalizedText.Language.German] = new ConfigLocalizationEntry("RESET-SEKUNDEN", "Wie lange ein Spieler ohne zu pingen bleiben muss (bei vollständig geleerter Warteschlange), bevor der Slow Mode vollständig zurückgesetzt wird."),
                [LocalizedText.Language.SpanishSpain] = new ConfigLocalizationEntry("SEGUNDOS PARA REINICIAR", "Cuánto tiempo debe pasar un jugador sin hacer ping (con su cola totalmente vacía) antes de que el modo lento se restablezca por completo."),
                [LocalizedText.Language.SpanishLatam] = new ConfigLocalizationEntry("SEGUNDOS PARA REINICIAR", "Cuánto tiempo debe pasar un jugador sin hacer ping (con su cola totalmente vacía) antes de que el modo lento se restablezca por completo."),
                [LocalizedText.Language.BRPortuguese] = new ConfigLocalizationEntry("SEGUNDOS PARA REINICIAR", "Quanto tempo um jogador precisa ficar sem pingar (com a fila totalmente esvaziada) antes que o modo lento volte totalmente ao normal."),
                [LocalizedText.Language.Russian] = new ConfigLocalizationEntry("СЕКУНДЫ ДО СБРОСА", "Сколько времени игрок должен не пинговать (при полностью опустевшей очереди), прежде чем медленный режим полностью сбросится в обычный."),
                [LocalizedText.Language.Ukrainian] = new ConfigLocalizationEntry("СЕКУНДИ ДО СКИДАННЯ", "Скільки часу гравець має не пінгувати (з повністю спорожненою чергою), перш ніж повільний режим повністю скинеться до звичайного."),
                [LocalizedText.Language.SimplifiedChinese] = new ConfigLocalizationEntry("重置秒数", "玩家需要停止呼喊多久（且队列已完全清空）后，慢速模式才会完全重置为正常状态。"),
                [LocalizedText.Language.TraditionalChinese] = new ConfigLocalizationEntry("重置秒數", "玩家需要停止呼喊多久（且佇列已完全清空）後，慢速模式才會完全重置為正常狀態。"),
                [LocalizedText.Language.Japanese] = new ConfigLocalizationEntry("リセットまでの秒数", "プレイヤーがピンを送らない状態（キューが完全に空になった状態）をどれだけ続けると、スロー モードが完全に通常へリセットされるか。"),
                [LocalizedText.Language.Korean] = new ConfigLocalizationEntry("초기화까지의 시간(초)", "플레이어가 핑을 보내지 않은 상태(대기열이 완전히 비워진 상태)를 얼마나 유지해야 슬로우 모드가 완전히 정상으로 초기화되는지입니다."),
                [LocalizedText.Language.Polish] = new ConfigLocalizationEntry("SEKUNDY DO RESETU", "Jak długo gracz musi nie pingować (przy całkowicie opróżnionej kolejce), zanim tryb spowolniony w pełni wróci do normalnego stanu."),
                [LocalizedText.Language.Turkish] = new ConfigLocalizationEntry("SIFIRLAMA SÜRESİ (SANİYE)", "Yavaş modun tamamen normale sıfırlanması için bir oyuncunun (kuyruğu tamamen boşalmış halde) ne kadar süre ping atmadan durması gerektiği."),
            });
        }
    }
}
